### ISSUE TITLE
Refactor Protocol to consume tokens

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#109]
We need to refactor protocol to consume all of our design tokens and to work with any new naming conventions.

**Comment by alexgibson** [comment]
It would be nice to try and get this one done soon, as I'm trying to reference CSS variables in the mozorg home page for colors that don't exist in the older tokens repo 👍

**Comment by alexgibson** [comment]
Blocked by https://github.com/mozilla/protocol-tokens/issues/9

**Comment by alexgibson** [comment]
Blocked by https://github.com/mozilla/protocol-tokens/pull/14

**Comment by alexgibson** [comment]
Blocked by https://github.com/mozilla/protocol-tokens/issues/16

**Comment by alexgibson** [comment]
\o/
