### ISSUE TITLE
Set some goals for Q3 and Q4

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#124]
The end of Q2 is upon us and we've been reflecting on our progress since this all started at the beginning of the year. It's also time to start looking forward and setting some tangible, realistic goals for what we want to accomplish in the second half of the year and where we want to go beyond that. We'll make a wish list, then start to narrow it down and put things in order of priority. I'll start with a bunch of stuff we've already been discussing:

- ~Rebuild the mozorg home page in bedrock using Protocol components (actually a Q2 goal).~
- Make a standardized Firefox campaign landing page template with room for some variation, different combinations of components, etc.
- ~Get the Protocol site up at protocol.mozilla.org.~
- Redesign the Protocol site.
- Port the security pages to Protocol.
- Port more text/article pages to Protocol (/foundation, /privacy, etc).
- Overhaul the mozorg information architecture and redesign the main navigation (not technically a Protocol goal, but this IA work paves the way for a lot more stuff; this is more of a whole durable team goal).
- Redesign the About Mozilla page (actually a few pages, maybe the whole section, pending IA).
- Redesign the Contribute pages.
- Death to Sandstone.
- Redesign the Technology page (or figure out what to do with it, pending IA).
- Redesign the Internet Health hub and sub-pages.
- Redesign the Developer hub page.
- Redesign the Firefox product page(s).
- Redesign careers.m.o
- Redesign support.m.o

**Comment by alexgibson** [comment]
> Make a standardized Firefox campaign landing page template with room for some variation, different combinations of components, etc.

I think many external teams will want this, and it could be a good use of our component system to prove just how fast a well built design system can help us work.

> Overhaul the mozorg information architecture and redesign the main navigation (not technically a Protocol, but goal this IA work paves the way for a lot more stuff; this is more of a whole durable team goal).

Even though this isn't strictly related to Protocol, I'd like us to try and prioritize this if possible, as the component touches every page we'll build. The longer we delay it, the more long term technical debt we'll build up. 

> Redesign the About Mozilla page (actually a few pages, maybe the whole section, pending IA).
> Redesign the Contribute pages.

If we we're gonna do any opther mozorg pages, these would be my 2 top picks.

> Redesign careers.m.o
> Redesign support.m.o

I think we should commit to at least one of these (2 may be pushing it, unless we cleared some more items off the table?)

**Comment by djst** [comment]
Adding to the list above: 

**Self-service production of pages by other (non-Mozilla.org) teams**
- We want Winston and other team members to be able to reach a higher level of autonomy by being able to build certain web pages 90% on their own, with the Mozilla.org team only spending the last 10% of QA and review. This frees up lots of resources for Mozilla.org team being able to work on other things instead. It also helps other teams work faster.
- Roadmap needs to include a plan for how this autonomy will be enabled.
- We also need to sandbox this autonomy to known user journeys. Example of a user journey that could be owned entirely by another team: paid-media Firefox download landing page iterations. This traffic will not be controlled by Moz.org team, now will we control the creative process. Entirely appropriate for Winston’s team to own production and performance of this page - so long as it uses the provided Protocol components/page templates and we’ve done the QA/pushed the buttons to get the page out live.

**Multivariate testing capabilities**
- There’s a huge demand for something that allows teams to test iterations of web pages quickly - including ourselves as we build our own pages, but also for other teams across the org. 
- With a robust design system in place, how can we leverage it for testing?

**Comment by djst** [comment]
Roadmap needs to include info about how we’ll assess which pages to rebuild, and the timeline for that work. 
- A big chunk of work ahead of us is building out all missing components. This work will also be an opportunity to update (and sometimes obsolete/delete) existing pages like the /About section. How will we priorize this work? 
- I think we’ll prioritize based on traffic/popularity, but also strategic opportunity, something like:
- About section, Get involved section - because they’re in the main nav and gets relatively more traffic than many other pages
- Careers website redesign - strategic opportunity for Stephanie to “test/QA” Protocol as a semi-outsider. Why Careers before SUMO? It’s a smaller website. The promise is that Stephanie also feeds Protocol team with input on things that need to change/improve before other third parties can use it. That gives us valuable input allowing us to extend Protocol to other third parties, such as:
SUMO website redesign - assuming Careers website was successful, The Brigade can now take on another redesign and use Protocol entirely. 
- Throughout this work, new components will be added. 

Roadmap should answer the question why we chose the order we chose for all this work.

**Comment by thejeffreytaylor** [comment]
We need to discuss how my Content Strategy work will fit into this. As I see it, beyond day-to-day SME consult with our durable team work and a large role in the IA/Nav re-do, I'm focused on three deliverables here: 

1. My parts of the design system (completion of A11y, voice/tone, terminology lexicon, etc.)

2. Moz.org Permanent Content Audit - I've got a proposal as issue [#5770](https://github.com/mozilla/bedrock/issues/5770)

3. User Journeys and Content Mapping - I'll be adding a proposal to issues [#5772](https://github.com/mozilla/bedrock/issues/5772)

**Comment by alexgibson** [comment]
Ok, based on the past couple of meetings we've had, I'm gonna try and take a stab at a final list of formal deliverables:

1. Redesign /about:
  - Preliminary IA & content strategy work.
  - Design & development of any new components it may require.
  - Build new bedrock pages using the newly created Protocol components.
2. Redesign /contribute:
  - Preliminary IA & content strategy work.
  - Design & development of any new components it may require.
  - Build new bedrock pages using the newly created Protocol components.
3. Firefox download page variations.
  - Take Mark's design work and port the newly designed components to Protocol.
  - Using these components, build a set of download page templates.
  - Find a place where these templates can live (on the Protocol site?) where people can download and edit them.
4. Careers site.
  - Redesign the careers.mozilla.org site using Protcol components.
5. Anything else? (how much more can we realistically fit in)

**Comment by alexgibson** [comment]
@djst can we close this issue as done? I think we have a pretty good idea of our next steps here.

**Comment by djst** [comment]
Hey @alexgibson and others, thanks for the above! I had missed this thread and have focused on building out https://docs.google.com/document/d/19kHHVj10G5qXqBmR_yblTcBCj7gU2FULvVqY2Snt_Dc/edit#. Mostly it's mirroring this, but there's one notable exception: I haven't included /contribute (but I can), and I had not seen the Firefox download page variations. I think that's a worthy addition. 

So yeah, I *think* we can close this one, and we'll continue the work in the document that I needed to write anyway to share out with MEM/Chad etc. (Which I haven't done yet, but will soon after some of the edits above.)

Thanks!!

**Comment by alexgibson** [comment]
Ok thanks, I'm going to close this and update our [roadmap board](https://github.com/mozilla/protocol/projects/5) with what's here.
