### ISSUE TITLE
Wishlist: Component: Accordion

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#129]
We need an element for collapsing and expanding content. 

We can look at where mozilla-accordion.js is used for use cases. [This page](https://www.mozilla.org/en-US/privacy/firefox/) doesn't seem to use that library though.

It would be nice to base it on something semantic like`<details>` and `<summary>` if they have sufficient support.

**Comment by alexgibson** [comment]
+1 for leveraging as many native browser features as we can. There may be some form of polyfill available for non-supporting browsers too, but would require some further investigation.

**Comment by thejeffreytaylor** [comment]
I have suggested this interaction quite a bit in the past, for what it's worth, and don't see that stopping here given what I see about the culture of content at Mozilla.

**Comment by alexgibson** [comment]
Depends on #184
