### ISSUE TITLE
Include newsletter form submission JS

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#131]
Currently the Protocol newsletter component contains JS to handle expanding the form contents, but nothing to handle submission of the form to Basket. We point people to the [basket example lib](https://github.com/mozilla/basket-example/), but this library was written for the old Sandstone newsletter form, and many of the CSS class names and ID's have changed. To get it working again is a bit of a chore, so I think we should consider including some updated JS in Protocol to take care fo this.

There was some concern that we shouldn't include a fully functional signup form in the Protocol docs itself, so we could build a toggle to disable form submission when set for example purposes.

**Comment by alexgibson** [comment]
Form should also allow for a custom callback on sucessful submission, to allow sites to track subscriptions on a per-page basis.

**Comment by craigcook** [comment]
Related to https://github.com/mozilla/protocol/issues/255

**Comment by alexgibson** [comment]
Closing as a duplicate of https://github.com/mozilla/protocol/issues/839
