### ISSUE TITLE
Need a Q3+Q4 roadmap summary along with a clear resource ask

### ISSUE THREAD

**Issue by djst** [mozilla/protocol#133]
This depends on / is blocked by #124.

We need to put together a high-level roadmap summary for 2H 2018 that I can present to MEM/Chad/Jascha when asking for resources (primarily designer resources). 

MEM wrote an email with the following request:

> Some of the specifics I’d be interested in…
-details on testing plan, including multivariate testing 
-how this work aligns with the IA/navigation work
-how you’ll assess which pages to rebuild, and the timeline for that work
-how the “self service” aspects of the system will be rolled out
-resources needed to deliver on this work

I need this by the end of this week - and be ready to present during all hands. :)

**Comment by alexgibson** [comment]
Can this be closed?

**Comment by djst** [comment]
Result is here: https://docs.google.com/document/d/19kHHVj10G5qXqBmR_yblTcBCj7gU2FULvVqY2Snt_Dc/edit#
