### ISSUE TITLE
Remove .mzp-c-card-small-cta style

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#136]
There is a card on the homepage with an underline(on hover) that extends the full width of the card in Firefox. Adding `width: -moz-fit-content;` should fix this issue

![screen shot 2018-06-04 at 8 40 17 am](https://user-images.githubusercontent.com/5924575/40927181-f1fd55e6-67d2-11e8-9456-ffc7a7e86bb9.png)

**Comment by alexgibson** [comment]
This isn't going to be part of the home page (these card types don't exist any more). But we could still either fix the underline, or remove that style entirely.

**Comment by alexgibson** [comment]
A non-vendor specific fix would also be to use `display: inline;`, as there's no real reason the element needs to be block-level;

**Comment by vincejoyiv** [comment]
@alexgibson yes, for now. I think as we make these cards more useful in other contexts, we'll find that we need some kind of CTA link. But we can cross that bridge when we get there.
