### ISSUE TITLE
Update hover state for Card component

### ISSUE THREAD

**Issue by vincejoyiv** [mozilla/protocol#137]
Hey @alexgibson just noticing a couple small things on the card hoverstate.

- the box-shadow color should be "Gray 20" the hex value of which is `#EDEDF0`
- I'd like to do a border-bottom of 2px instead of 1.

That ends up looking like [this](https://www.dropbox.com/s/vbgtkh06xb2epvo/Screenshot%202018-06-04%2009.16.15.png?dl=0).

**Comment by alexgibson** [comment]
This was done in #109
