### ISSUE TITLE
Test links and show a alert if not statuscode 200

### ISSUE THREAD

**Issue by rraue** [mozilla/protocol#142]
If it's possible, we should try to show an alert if links arent entered correctly or are pointing to a 302/1. For example if the component button, like in the screenshot below has a link value but the value is https//www.mozilla.org/en-US/firefox/.

![image 1](https://user-images.githubusercontent.com/36700618/41131146-ff8a7664-6a6e-11e8-9cfa-196066db1eee.png)

A yellow alert for 301/2 would be good and for a 404 a red one!?

**Comment by alexgibson** [comment]
While this is an interesting idea, I'm not sure if the design system is the right place to test things like response codes imho. The button component editor is only for making pseudo-code or examples that can be used in mockups. What's created here would not necessarily match the code that gets used in production (django uses url helpers to create our internal links for example). If we want to avoid 300 responses in our links, this should be unit tested in bedrock.

**Comment by stephaniehobson** [comment]
I agree with Alex. Protocol doesn't have any links in it that should make it to a production website. The place to test those things is the production website code. Also, I don't think the button editor is part of the site code anymore.
