### ISSUE TITLE
Remove the image link from the billboard molecule

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#143]
The billboard (https://protocol.mozilla.org/patterns/organisms/billboard.html) includes a link for the image but in all the uses of that component so far the image is presentational and has an empty alt attribute. I don't think the image should be a link if it's not essential content. If we want a large hit area for clicks we could make the entire billboard a block-level link, or else leave it with just the CTA text link.

**Comment by alexgibson** [comment]
This is getting picked on Lighthouse as an a11y issue, so I'm going to upgrade this from wishlist to a bug: https://www.webpagetest.org/lighthouse.php?test=180703_DH_4ab83e128fbebcb53d7077ceba9b185a
