### ISSUE TITLE
Pseudolocalization support

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#144]
In the current component editor we're displaying alerts / warnings for things like character count on buttons / titles. This is useful for English pages, but becomes slightly less useful for localized pages where translations can be considerably longer. It could be nice to expand this functionality in the future to help test our components under different translation contexts, in a similar fashion to how Firefox is doing things:

https://diary.braniecki.net/2018/06/07/pseudolocalization-in-firefox/

This could really help us test how flexible our components are under different conditions, before they get to www.mozilla.org. It would also make it much easier to test & demo RTL layouts.

**Comment by Deepikap1** [comment]
@alexgibson, can you please clarify how it becomes less useful for localized pages?

**Comment by stephaniehobson** [comment]
I pulled the function that they're using in Firefox out and made an addon with it: https://addons.mozilla.org/en-US/firefox/addon/pseudolocalize/

It should be pretty easy to re-use in the protocol component editor if we want to embed it on the page.
