### ISSUE TITLE
Utility Classes for Background Colors

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#151]
Create utility classes (i.e. `.background-blue`) that apply a background color to a component using the color design tokens

**Comment by alexgibson** [comment]
This seems like it will be used in various landing page components, so probably makes sens to land first. @michaelmccombie - do we want utility classes for every token color, or just a select pallet?

**Comment by michaelmccombie** [comment]
Closing this for now as we explore having a handful of page themes and tackle different colored sections on a case by case basis.
