### ISSUE TITLE
Section with a Headline and Paragraph

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#152]
**Variations**
- A utility class can be applied to the background color
- The text can be either black or white

**Notes**
- The component itself shouldn't have a max-width so the background color will stretch to the edge of the screen
- The text has a max-width of 608px

**Desktop (1024px)**
<img width="768" alt="image" src="https://user-images.githubusercontent.com/5924575/41958209-357fa0b2-799e-11e8-855c-fc873992548b.png">

**Mobile (480px)**
<img width="484" alt="image" src="https://user-images.githubusercontent.com/5924575/41958139-fea936b6-799d-11e8-8385-5316e2bc2160.png">

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/protocol/issues/151

**Comment by alexgibson** [comment]
@michaelmccombie is it safe to assume that this component mainly purposed for being a header for a section, as opposed to a section in itself?

**Comment by michaelmccombie** [comment]
This is intended to be its own section, which can be color blocked to distinguish it from other sections. 

For what it's worth, we might not need to write any new custom classes for this component. It's simple enough we might be able to create an example with what we already have. Just need to throw it in the documentation site somewhere.

The is similar to this example from Slack:

![image](https://user-images.githubusercontent.com/5924575/42175668-136c7270-7ddb-11e8-9f53-cf454c6c4afa.png)

**Comment by alexgibson** [comment]
> The is similar to this example from Slack:

This example has a CTA however, so is closer to https://github.com/mozilla/protocol/issues/153. Do we think we no longer have a use for this component?

**Comment by alexgibson** [comment]
This is no longer needed
