### ISSUE TITLE
Call Out Section

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#153]
This section can include any combination of these four elements:
- Logo
- Headline
- Description
- CTA

The plan is for this section to be theme-able. The Mozilla theme, for instance, would use the Zilla-Slab font for its headlines.

![image](https://user-images.githubusercontent.com/5924575/42201651-a58fc3ba-7e4d-11e8-918e-0ea461f91867.png)

**Comment by alexgibson** [comment]
PR to add Firefox logos to the assets repo: https://github.com/mozilla/protocol-assets/pull/6
