### ISSUE TITLE
Section with two columns

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#155]
**Desktop (1024px)**
<img width="573" alt="image" src="https://user-images.githubusercontent.com/5924575/41959048-ca602ea2-79a0-11e8-9df5-c84d05a60e8d.png">

**Mobile (480px)**
<img width="288" alt="image" src="https://user-images.githubusercontent.com/5924575/41959071-d4f4f190-79a0-11e8-9573-a78bb2f1bd48.png">

**Comment by alexgibson** [comment]
It makes sense to bundle this with #154

**Comment by alexgibson** [comment]
Closed via https://github.com/mozilla/protocol/commit/6e0bd14a134fd35b5063fe7501eafa8d3e89cf87
