### ISSUE TITLE
Section with media

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#156]
**Variants**
- The background color is interchangeable
- Media is interchangeable
- Video has a 16:9 aspect ratio with a max-width of 864px
- Images have a max-width of 864px

**Note**
- The overlap is intentional

![image](https://user-images.githubusercontent.com/5924575/41959469-ec350e8e-79a1-11e8-9af3-2728941b316b.png)

**Comment by craigcook** [comment]
I think this is superseded by #326
