### ISSUE TITLE
Hero Section - Centered Text

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#157]
**Variants**
- The background color is interchangeable 
- A background image can be applied

**Notes**
- It would nice (definitely not a requirement) if we could apply a dynamic bezier curve animation similar to this example.
https://www.joshwcomeau.com/posts/dynamic-bezier-curves

**Desktop (1024px)**
<img width="564" alt="image" src="https://user-images.githubusercontent.com/5924575/41959666-7f03935c-79a2-11e8-9a5b-5637cd0bd5d5.png">
<img width="552" alt="image" src="https://user-images.githubusercontent.com/5924575/41959845-f8174702-79a2-11e8-9fde-2240e1438d3b.png">

**Mobile (480px)
<img width="284" alt="image" src="https://user-images.githubusercontent.com/5924575/41959883-13ae0050-79a3-11e8-9cde-586e6ddaa0d2.png">

**Comment by alexgibson** [comment]
PR to add Firefox logos to the assets repo: https://github.com/mozilla/protocol-assets/pull/6
