### ISSUE TITLE
Hero Section - Mozilla Theme

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#158]
Similiar to the other hero section components.
- Zilla-Slab as the headline font. 
- Doesn't include a logo. 
- Includes an image which can be either left or right aligned.

Desktop (1024px)
<img width="561" alt="image" src="https://user-images.githubusercontent.com/5924575/41960196-ff9c787a-79a3-11e8-8e4d-053e4c01f7ac.png">

Mobile (1024px)
<img width="297" alt="image" src="https://user-images.githubusercontent.com/5924575/41960350-626d3796-79a4-11e8-8636-ad6ba6f265d7.png">

**Comment by michaelmccombie** [comment]
@craigcook We might want to combine this with #157 or at least use the Open Sans font and build out a Firefox version first and then theme to Mozilla later when we tackle page themes.

**Comment by craigcook** [comment]
It seems like the Mozilla style should be the baseline "unthemed" theme for all of Protocol, then Firefox would be a theme applied on top of that. That's a little backwards for the landing page stuff since we know it all needs to be Firefox themed, but it feels like the more practical approach.
