### ISSUE TITLE
Create new button styles for landing page components

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#167]
A few different landing-page components feature new blue & black button styles:

https://github.com/mozilla/protocol/issues/158
https://github.com/mozilla/protocol/issues/157
https://github.com/mozilla/protocol/issues/153

To save save work, we should create a separate PR for this new style. We should also make sure to update the newsletter component to use the new black button style:

https://protocol.mozilla.org/patterns/organisms/newsletter.html

**Comment by michaelmccombie** [comment]
The gradient for the download button should be 

Default State
$color-green-50 to $color-green-70

Hover State
$color-green-60 to #color-green-80

Here's an image of the new download button style
![image](https://user-images.githubusercontent.com/5924575/42363225-91b713d8-80ab-11e8-8ee9-2a872e826479.png)
