### ISSUE TITLE
Add a fundamentals page for content sizing & breakpoints

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#176]
It would be helpful for both designers & developers to have a reference page that details our common page/content sizes and breakpoints.

The only way to find this info currently is in the tokens source code: https://github.com/mozilla/protocol-tokens/blob/master/tokens/_aliases.yml#L127-L144

**Comment by craigcook** [comment]
We added a tokens page at https://protocol.mozilla.org/fundamentals/tokens.html which at least gives us an easier reference for these values, though I think we could expand on it with more context and guidelines. Closing this issue as "good enough for the moment."
