### ISSUE TITLE
Add pages that list all assets.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#177]
As per @craigcook's suggestion, a page that lists all our tokens for reference would also be useful. We could also do the same for our image assets/icons.

https://github.com/mozilla/protocol-tokens
https://github.com/mozilla/protocol-assets

**Comment by alexgibson** [comment]
The tokens page is done, but I'm moving this back to to-do so we can add a page that lists assets.

**Comment by craigcook** [comment]
This is on hold pending new icons, we'll reopen when we're ready: https://github.com/mozilla/protocol-assets/issues/82
