### ISSUE TITLE
Localization guidelines

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#18]
> Our sites serve a global audience and should translate well across nations, cultures, and languages. Green might not always mean go, symbols and idioms have very different meanings to different people, fonts and text will vary and reflow. Plan for a wide reach and design for localization.

We should document some basic dos and don'ts around designing for l10n.

**Comment by thejeffreytaylor** [comment]
Will not get to this in the work week, but will get there.

**Comment by craigcook** [comment]
There's been no movement on this for a while, closing as irrelevant for now. If we want to revisit the idea at a later time we can reopen or start fresh.
