### ISSUE TITLE
Update Footer Component

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#184]
We need to update our generic footer component in Protocol.  
There are a couple of things to note:

- The footer going into mozilla.org has four columns. Ideally, this component should be flexible enough to allow developers to include anywhere from 2 to 6 columns.

- Almost every part of the footer should be optional. The disclaimer should be required (which we could mention on the documentation page).

- The language selector and the social icons should appear above the disclaimer (we might have to use some CSS Grid trickery to get this working, it's okay to have things appear in a different order in IE6).

- The content in the bottom half of the footer (disclaimer, language, social icons) should be aligned/ anchored to the corners. There is an example below.

- The social icons should launch a modal asking the user which account page they would like to visit (i.e. Firefox's Twitter or Mozilla's Twitter). There is an example below with some temporary visuals. That should be updated soon.

## Desktop (1024px)

_Example with content_
![image](https://user-images.githubusercontent.com/5924575/43186202-dcb96448-8fa2-11e8-97f1-49630bc414ce.png)

_Six column option_
![image](https://user-images.githubusercontent.com/5924575/43186521-b1659112-8fa3-11e8-8520-49d986d9413f.png)

_Four column option_
![image](https://user-images.githubusercontent.com/5924575/43186094-937d35ca-8fa2-11e8-8c08-b6b524ed46cd.png)

_Three column option_
![image](https://user-images.githubusercontent.com/5924575/43186393-616defce-8fa3-11e8-9d46-4a43c679aa17.png)

_Two column option_
![image](https://user-images.githubusercontent.com/5924575/43186260-071cb6a4-8fa3-11e8-9d70-6ce148efa339.png)

## Tablet (768px)

_Example with no content_
![image](https://user-images.githubusercontent.com/5924575/43186625-1a11dd10-8fa4-11e8-91a2-39d3d3caf967.png)

## Mobile (480px)

_Example with content_
![image](https://user-images.githubusercontent.com/5924575/43186842-c43637c8-8fa4-11e8-8659-300730a82448.png)

_Example with no content_
![image](https://user-images.githubusercontent.com/5924575/43186698-4fb8e4d6-8fa4-11e8-9279-7ce5bd2069cd.png)

## Variants
_ No List Items_
![image](https://user-images.githubusercontent.com/5924575/43187210-b33e862c-8fa5-11e8-9821-51c6cba9c3be.png)

## Visual Notes
_Required/ Optional_
![image](https://user-images.githubusercontent.com/5924575/43187630-cf2f4e06-8fa6-11e8-888a-94ab0645cd69.png)

_Content anchored/aligned to the corners_
![image](https://user-images.githubusercontent.com/5924575/43188346-ba447a3c-8fa8-11e8-9b5b-da4d69feef75.png)

## Social Links
We might want to support multiple accounts in the future either through a modal or sending users to a new page with additional links, but for now, these social links will send users to Mozilla's social accounts on mozilla.org. 

![image](https://user-images.githubusercontent.com/5924575/43188541-2ee1d6f0-8fa9-11e8-9d5a-318c3a8d5e82.png)

**Comment by alexgibson** [comment]
Note: we already haver a footer component in Protocol, so this would just be updating the existing one that's already in use.

My focus right now is on the nav and the footer was not part of the original scope for this initial sprint, so I'm unassigning this for now and someone can pick it up when we get this prioritized.

**Comment by alexgibson** [comment]
As a side note: it would be great to find an alternate solution for the social links that doesn't require a modal. The footer appears on every page of the site, so requiring the modal CSS & JS as a dependency on every page could be a high overhead (considering the amount of people who likely click these icons).

**Comment by michaelmccombie** [comment]
@alexgibson that's a really good point.  

As an alternative what do you think about creating a new list page with just our social media accounts listed on it (similar to the Language Selector page). The problem we are facing is that we have at least two accounts for everything.

![screen shot 2018-07-25 at 11 34 40 am](https://user-images.githubusercontent.com/5924575/43220376-c1addd9e-8ffe-11e8-9aa8-26bfc1ac7b78.png)

**Comment by michaelmccombie** [comment]
I spoke with Jennifer earlier today, her suggestion is for us to just support the Mozilla links for now. 

We'll keep the list page idea as an option if somewhere down the line we are asked to have links for the multiple accounts again. But we don't have to worry about it for this project.

**Comment by dzingeek** [comment]
My suggestion is to only have the moz social icons in the footer. We can find better places to highlight fx ones on pages that are about fx.

**Comment by stephaniehobson** [comment]
Demo is online here: https://demo1--mozilla-protocol.netlify.com/demos/footer.html

Still cleaning up the Protocol documentation.

**Comment by stephaniehobson** [comment]
Demo is updated with proper documentation: https://demo1--mozilla-protocol.netlify.com/

Initial PR is here: mozilla/protocol#237
