### ISSUE TITLE
Additional modal options

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#187]
The modal we currently have in Protocol works great for video, but we have an upcoming project that needs a smaller modal with a light-theme. More details coming soon.

**Comment by alexgibson** [comment]
The modal we have currently is built to display any kind of HTML content. We may be able to add some more config/theming options to it, rather than build a second component - but it depends on the requirments.

**Comment by michaelmccombie** [comment]
I updated the title. This project needs a pretty basic modal similar to what Bootstrap offers.
https://getbootstrap.com/docs/4.0/components/modal/

![image](https://user-images.githubusercontent.com/5924575/43343889-c47e8fc4-919c-11e8-94dc-eb4912cbaf60.png)

**Comment by stephaniehobson** [comment]
In lieu of requirements I suggest we begin with some over-rides that have already been applied on bedrock.

#358 #357

**Comment by stephaniehobson** [comment]
See also #358 #357

**Comment by ehot** [comment]
To align with FF design system.

**Comment by craigcook** [comment]
We'll be redesigning/rebuilding the modal component soonish and the new one can have more options. Closing this as it'll be superseded by another task.
