### ISSUE TITLE
Create landing page template demo files

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#189]
When the last landing page component is complete, we should construct some full-page templates that demonstrate the components in different combinations, similar to Mark’s initial work in Sketch. This will be a good opportunity to demonstrate how the components can be used together, and also how Protocol can be used in its entirety.

These templates could live in the protocol documentation site, or alternatively be in their own repo that consumes Protocol as a dependency (in the same way bedrock does). The latter might be useful as we could publish releases of the templates independently and distribute the zip files more easily.

**Comment by alexgibson** [comment]
Depends on 
https://github.com/mozilla/protocol/issues/156

**Comment by craigcook** [comment]
We still want to get to this some day, but closing out stale issues. We can always reopen or replace when we get back around to it.
