### ISSUE TITLE
New CTA button style

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#198]
First time I've seen the [Pocket page](https://www.mozilla.org/en-US/firefox/pocket/) today, but I notice there's a new button style that's not yet in Protocol. 

We should add this - It seems like a new CTA button style perhaps (with unique hover style?), or could this be a new default button style for dark backgrounds?

**Comment by stephaniehobson** [comment]
The same button styles are also on the [Accounts Features](https://www.mozilla.org/en-US/firefox/accounts/features/) page.
