### ISSUE TITLE
Hero component should vertically center text

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#199]
It gets awkward at some screen sizes right now.

<img width="725" alt="screen shot 2018-08-03 at 15 38 08" src="https://user-images.githubusercontent.com/854701/43668740-4d5e2d72-9733-11e8-8681-b4f9df9a1c7e.png">

But maybe this isn't the most common use case? Not sure what was in mind when it was created.

**Comment by stephaniehobson** [comment]
Yeah, I had a min-height for the background image.

**Comment by stephaniehobson** [comment]
Needed this again on the new desktop and mobile pages (which have images and the content therefore expands taller than the text).

We could add v-top, v-middle, v-bottom utility classes to the hero like we plan for the block component.

**Comment by Aakash2408** [comment]
Is someone working on this or I can take this?

**Comment by maureenlholland** [comment]
closing as we have deprecated the hero component

**Comment by maureenlholland** [comment]
closing as we have deprecated hero component
