### ISSUE TITLE
Page hero shape mask needs -webkit prefix for some browsers

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#213]
https://caniuse.com/#search=mask

The Protocol doc site uses autoprefixer so we didn't notice this initially. Bedrock doesn't currently use autoprefixer (though I'd like to) so the shape mask doesn't appear in current Safari (it does appear in current Chrome but likely not in older Chromes). We should emphatically include the prefixed properties in the Protocol SCSS for use downstream.

On the other hand, we could consider this progressive enhancement in action (it's in an @supports feature query) and the no-mask fallback state can be considered intentional. How far backwards do we want to bend for Safari?

**Comment by alexgibson** [comment]
> The Protocol doc site uses autoprefixer so we didn't notice this initially.

I think untril we figure out a long term plan for how we handle prefixes (in both protocol and bedrock), I'd be in favor of removing auto-prefixer from the Protocol docs so our generated CSS is always the same (see also https://github.com/mozilla/protocol/issues/119).

**Comment by craigcook** [comment]
Agreed, we should remove autoprefixer.

**Comment by stephaniehobson** [comment]
Removed in #311
