### ISSUE TITLE
Update visual style of Global header nav on desktop

### ISSUE THREAD

**Issue by vincejoyiv** [mozilla/protocol#216]
Links to resources:
[Sketch File](https://share.goabstract.com/487103ba-5ee4-44a0-b335-337e8cf6e465)
[Motion Prototype](https://www.dropbox.com/s/1noa2uqvk23n9u4/Mozilla_RevisedNavigation_Protoype_20180830%202.zip?dl=0)
[Card Component Prototype](https://codepen.io/vincejoy/pen/NLGdPx)
[Text Link Hover Effect Prototype](https://codepen.io/vincejoy/pen/XPNOmE)

### Updates to the current version:
- Header link font weight is bold
- Header links have 24px padding on the left
- Download button is Small (32px height) to match the height of the Mozilla logo
- When the nav is active, the four main links get a bottom border of 2px, Gray 20 (#ededf0), that spans the full width of the links—from Firefox to About— and is aligned to the bottom edge of the Mozilla logo
- The active tab has a bottom border of 2px, Black
- The active link shifts up 2px
- The ‘Close’ button is on the same line as the links, 24px to the right of the Download button
- The entire panel has border-bottom of 4px solid black (no soft shadow)
- Vertical space updates (see spacing specs in Sketch file)
- Card
  - Updated card design allows the text to line up directly to the left edge of the image
  - Hoverstate: image moves up 2px and left 2px. image gets a hard drop-shadow that extends down and left 4px. The card gets a 2px black underline that animates slightly from the left [See this codepen](https://codepen.io/vincejoy/pen/NLGdPx)
- Hoverstates
  - No more gray border around sections. 
  - Animate the border bottom element [See this codepen](https://codepen.io/vincejoy/pen/XPNOmE)
- Text Color
  - Link text should be Black (#000000)
  - All description text should be Gray 70 (#38383D)

**Comment by alexgibson** [comment]
As soon as we've rolled out the new nav for all locales, I'd like to add this to one of our upcoming sprints to get done. Added to our team's backlog for now.

**Comment by dzingeek** [comment]
There is a modular nav system being worked on that may put this on hold? https://github.com/mozilla/protocol/issues/544

**Comment by alexgibson** [comment]
Superseded by https://github.com/mozilla/bedrock/pull/9650
