### ISSUE TITLE
Create a narrow/compact variant of the newsletter form

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#225]
The [updated /download/thanks/](https://www.mozilla.org/en-US/firefox/download/thanks/) page is ostensibly built with Protocol but displays a slightly modified version of the [newsletter organism](https://protocol.mozilla.org/patterns/organisms/newsletter.html) that is a bit more compact and lacks an image. We should backport this into Protocol as a standard variant for easier re-use.

**Comment by SunveerSingh** [comment]
Hello, I would love to work on this issue, can you guide me so that I can get started.

**Comment by stephaniehobson** [comment]
Closing in favour of https://github.com/mozilla/protocol/issues/508

@SunveerSingh Thank you for being interested. I think the form stuff is too big to be a good contributor issue.
