### ISSUE TITLE
Link to NPM release on Protocol home page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#230]
We should include a link to the NPM package (plus the current version number) on the Protocol home page:

https://protocol.mozilla.org/

**Comment by janbrasna** [comment]
@alexgibson Adding a badge that does the job sounds sufficient? #977 

> ![Screen Shot 2024-08-25 at 17 15 44](https://github.com/user-attachments/assets/aabb4a07-27f0-4c63-bca7-f44680fe72d9)

**Comment by alexgibson** [comment]
@janbrasna I think that looks great, nice suggestion!
