### ISSUE TITLE
Create a base style for blockquotes and (maybe) a component for pull quotes

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#234]
The `blockquote` element currently receives no special styling, just resetting browser defaults so it looks like normal text. We need to design a general style for the `blockquote` element and possibly a fancier component for pull quotes, if we want to give them special treatment.

**Comment by michaelmccombie** [comment]
![image](https://user-images.githubusercontent.com/5924575/45643825-d2c48c80-ba70-11e8-9362-84e1f1c025f0.png)
