### ISSUE TITLE
Ambiguity between existing components

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#241]
When working on [this sketch file](https://share.goabstract.com/b1b28993-132c-41a0-8a49-f915128bcf38) for WNP63, I noted some ambiguity in both our designs and components, so thought I should file an issue for discussion.

The design features a top hero section, and then lists several features down the page. In my mind this page should use one [hero component](https://protocol.mozilla.org/patterns/organisms/hero.html), and then three [feature cards](https://protocol.mozilla.org/patterns/molecules/feature-card.html). 

My mental picture wasn't quite possible in reality. I had to settle for two hero components, and two feature cards. The [final web page](https://www-demo2.allizom.org/en-US/firefox/63.0/whatsnew/) does not match up quite fully to the sketch file for a few different reasons:

1. The mockup features images that bleed off the edge of the page for each section. Only hero components can do this, and feature cards cannot. For the blue section I ended up using a second hero just so the image could bleed off, which feels weird especially when it has no call to action.

![screen shot 2018-09-28 at 15 25 26](https://user-images.githubusercontent.com/400117/46214333-d25ea800-c332-11e8-9bfe-ad72c1ebf5e3.png)

2. For the other two features, I stuck with my guns and used feature cards. This was mainly to center the text vertically as the sections have quite tall images. Vertically centered text is something feature cards do, but hero components do not. The tradeoff here was that the images no longer run off the edge of the page.

![screen shot 2018-09-28 at 15 19 16](https://user-images.githubusercontent.com/400117/46213972-dfc76280-c331-11e8-8481-33c19a496e02.png)

3. The small header for "Here’s What’s New" can be rendered almost identically using either a [hero component](https://protocol.mozilla.org/patterns/organisms/hero.html), or a [call out](https://protocol.mozilla.org/patterns/organisms/call-out.html). I chose to use a call out since yet another hero for this tiny thing feels wrong.

![screen shot 2018-09-28 at 15 16 12](https://user-images.githubusercontent.com/400117/46214066-21f0a400-c332-11e8-965a-d424e3fb28a3.png)

My thoughts are this:

- We're building too many components that do very specific things well, but aren't quite flexible enough to be versatile as a result.
- We probably don't need both a hero and feature card component. Both are very similar. We probably also don't need the standard callout component (although the [compact version](https://protocol.mozilla.org/patterns/organisms/call-out.html#call-out-compact) is still unique enough).
- When looking at a sketch file, it's sometimes very hard to spot which compnent a designer is using, becuase things are tweaked often. Some sort of label for identification could be useful for developers.

**Comment by michaelmccombie** [comment]
I think these are good points. I think we should set aside some time while we are all in Portland next week to discuss this, the overall health of the system, and strategize some next steps. 

I recognize it's a busy week, but it shouldn't be too hard to find a spare half hour on one of those days.

**Comment by craigcook** [comment]
This is partially done and continues to be addressed by other work. Closing this as historical but other issues will truly resolve it when they're done.
