### ISSUE TITLE
Site header for other Mozilla domains

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#245]
There is a website coming up (mozilla.design) that will use Protocol but isn't mozilla.org.
There is a concern that having an identical header and jumping from one site to another might confuse users. So the proposal is to have a bit of text that sits next to the Mozilla.org logo and the menu justified to the right.

This should look similar to the Mozilla Berlin mock-up.

**Before**
![image](https://user-images.githubusercontent.com/5924575/46379753-b0c43000-c654-11e8-930c-0d6e31f19bf4.png)

**After (WIP)**
![image](https://user-images.githubusercontent.com/5924575/46380391-ee29bd00-c656-11e8-8145-b898789cb984.png)

**Comment by alexgibson** [comment]
This seems like something we can add easily enough add to the existing nav using a couple of configurable options 👍
