### ISSUE TITLE
Privacy links are rendered twice on hero demo page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#249]
<img width="692" alt="screen shot 2018-10-04 at 16 22 52" src="https://user-images.githubusercontent.com/400117/46547080-c179dd80-c8c2-11e8-907b-7e5b5a9ebf84.png">

**Comment by craigcook** [comment]
Looks like this happened when the privacy link was put in a separate block in  7f0762319db716b02429885bdae26ac0a5a2414f
Easy fix.
