### ISSUE TITLE
Replace 'Open Sans' font-family

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#252]
We've gotten approval for switching the font-family from 'Open Sans' to 'Sharp Sans'. 
We will have more details soon, but we might be launching this font with the Firefox Fights For You campaign.

Sharp Sans - Headlines, buttons
System Fonts - Everything else.

**Comment by stephaniehobson** [comment]
New fonts are so much trouble :(

**Comment by ejregithub** [comment]
Stephanie indicated this is not final, new fonts may come in.

@stephaniehobson  to ping @vincejoyiv about this.

**Comment by stephaniehobson** [comment]
Moving blocker to https://github.com/mozilla/protocol/issues/342

**Comment by stephaniehobson** [comment]
Also note that the new goal is: https://github.com/mozilla/protocol/issues/342#issuecomment-475324102

**Comment by stephaniehobson** [comment]
Closing in favour of #342
