### ISSUE TITLE
Convert Protocol ES5 to modern JS

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#255]
Since this issue was originally opened Bedrock has migrated much of its JS from ES5 to modern JS syntax, and now supports things like ES modules. We use webpack to transpile to ES5 for backward compatibility.

I'd like to do the same here for Protocol's JS components, so that we can enjoy more parity between writing for Protocol and writing for Bedrock.

Doing this will make it easier for other websites to consume Protocol in a modern build system. It will also unlock backporting things from Bedrock to Protocol, such as the Basket newsletter logic.

The Protocol JS components should be output in UMD format, to support the widest possible range of import / usage methods.

We'll need to test to make sure things import into Bedrock OK as we go.

**Comment by stephaniehobson** [comment]
Why not ES6 compiling to ES5?

**Comment by alexgibson** [comment]
> Why not ES6 compiling to ES5?

ES6 was renamed ES2015, so they are the same thing :)
