### ISSUE TITLE
Determine browser support levels

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#27]
As we begin developing real components and especially face issues of page layout and JavaScript we need to think about minimum browser support. A few thoughts:

- IE8 and lower don't support a lot of CSS features we now take for granted. On mozilla.org we opted to just stop serving full CSS to those browsers and serve lte IE8 a separate minimal stylesheet that just offers basic typography. Shall we do the same with Protocol? It just means creating that minimal style and writing up some guidelines for the conditional comments. Probably need to add the HTML5 shiv as well.

- IE9 doesn't support matchMedia without a polyfill. If we make use of matchMedia in Protocol components (which we very well could), do we include that polyfill or do we just ignore IE9?

- vendor prefixes ... we've talked about using PostCSS and autoprefixer but should decide how far back in time we want to go.

And then there's Grid... we should use it as much as possible but there will be places where it's not practical and/or redundant to build the same layout twice. In other places we could just use grid and let older browsers get a simpler, linear layout. It's going to be a case-by-case thing much of the time but we might want to establish some general guidelines.

**Comment by jpetto** [comment]
I've been typing and deleting in this text box for about 30 minutes.

This might warrant multiple discussions, but in the interest of moving forward, my gut says we start with our strategy on mozilla.org, but attempt to stay free of jQuery - at least on supported browsers (IE <= 8 could load jQuery if necessary to avoid a bunch of boilerplate JS).

It is premature to agree that any component relying on JS for layout will have a base/default/no-JS view for IE <= 8?

Are we also opening up the discussion for no-JS support here?

**Comment by alexgibson** [comment]
+1 for serving oldIE’s no JS at all.

I’d also vote for saying no to any large JS libraries or frameworks, such as jQuery. Adding them as a dependency adds a large overhead to a project. We should instead favour native JS & small polyfills instead whereever possible.

I also think we should also question assumptions like needing an accordion. The last time we used one in a bedrock page was some time ago. There’s now also `<summary>` and `<details>`, which provide a native solution in modern browsers. Maybe we could use that with a polyfill for older browsers? Same goes for modals with `<dialog>`.

**Comment by craigcook** [comment]
You're right, I don't know if we'll ever actually have an accordion, that was just an example of the kind of common UI widget that can come up and would require some JS. We shouldn't build any component until there's an actual need for it.

**Comment by stephaniehobson** [comment]
+1 for a lite CSS, no JS version of the site and I vote we make liberal use of it.

We should use a "cut the mustard" tactic when loading the JS so we serve the no JS version to old FF and Safari too.

I would really like us to be able to go full ES6... that means excluding IE10. Thoughts? Maybe we should add Babel to the pipeline?

**Comment by craigcook** [comment]
I feel like we have some tribal knowledge about our browser support but haven't really documented it anywhere. In any case, this is a stale issue so I'm going to close it for now to help clean up our backlog. We can reopen if there's anything more to discuss.
