### ISSUE TITLE
Add custom sizes/content for video modal

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/protocol#279]
We have been creating custom modals for different types of content other than the default full-screen media player.

Perhaps something like- 
- `.mzp-has-video` for modals specifically used for videos. Toggling figcaption being on black like currently.

<img width="1279" alt="screen shot 2018-12-07 at 2 53 57 pm" src="https://user-images.githubusercontent.com/30483988/49669645-012e8400-fa30-11e8-9c76-1866d15557bb.png">

- Default being white open space for content in preexisting `.mzp-u-modal-content` class.
- `.mzp-c-modal-medium` or `.mzp-c-modal-small` for smaller sizes.

**Comment by amychurchwell** [comment]
Example of custom smaller modal for non-video content.

<img width="673" alt="screen shot 2018-12-07 at 2 43 22 pm" src="https://user-images.githubusercontent.com/30483988/49670109-85cdd200-fa31-11e8-8bf1-7a4603a616e9.png">

**Comment by amychurchwell** [comment]
Also see - #226 about YT video.

**Comment by craigcook** [comment]
We're redoing modals, closing this and it'll be superseded by new work.
