### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#29]
There may be some dependencies that that we're no longer / not currently using. We should probably remove them from the project if so (they can always be added back later).

- babel-core
- babel-eslint
- babel-loader
- babel-preset-es2015
- gulp-gh-pages

**Comment by adityac8** [comment]
Hey @alexgibson Can I work on this?

**Comment by alexgibson** [comment]
@adityac8 sorry i already have a PR ready for this.

**Comment by adityac8** [comment]
Okay @alexgibson Do let me know if any other issue needs help 👍
