### ISSUE TITLE
Article h3s are bigger than article h2s

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#293]
The declarations are probably just inverted?

https://protocol.mozilla.org/demos/article.html

**Comment by alexgibson** [comment]
This kind of thing seems like something that we should probably fix at the atomic level? Many components could well benefit from being able to specify their own title sizes, as opposed to them being predefined like this at the component level.

**Comment by alexgibson** [comment]
Filed https://github.com/mozilla/protocol/issues/297

**Comment by stephaniehobson** [comment]
Everywhere I've used the article component has been with a lot of text and I'm not super excited by the idea of manually applying classes to each heading. I'm not sure it's even possible with some of the content we're importing.

**Comment by alexgibson** [comment]
> Everywhere I've used the article component has been with a lot of text and I'm not super excited by the idea of manually applying classes to each heading. I'm not sure it's even possible with some of the content we're importing.

I don't think we'd need to manually apply classes to each heading. If we had some common utility classes for headings, those could be used by components in just the same way, but still provide more flexibility than we have now.

**Comment by stephaniehobson** [comment]
I'm going to fix this quickly now because it is blocking https://github.com/mozilla/bedrock/issues/6822 but I like the solution offered in #355 in the long run.
