### ISSUE TITLE
Component for text content in side bar

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#294]
Before we can convert old templates to use Protocol we need an equiblalent for the old `side-reference` class.

<img width="378" alt="screen shot 2019-02-06 at 11 04 01 am" src="https://user-images.githubusercontent.com/854701/52366611-03e13180-29ff-11e9-9906-371943cf97f3.png">

I think it could also be useful on the release notes page:

<img width="1038" alt="screen shot 2019-02-06 at 11 05 17 am" src="https://user-images.githubusercontent.com/854701/52366648-1d827900-29ff-11e9-95c2-a781f91c7799.png">

**Comment by alexgibson** [comment]
Could we alleviate the need for another new component here, if we fixed things at the atomic level? I may well not understand the full context, but at a high level view this looks like regular content inside a container?

There are several issues open discussing things like [grid](https://github.com/mozilla/protocol/pull/244), [narrow width containers](https://github.com/mozilla/protocol/issues/232) and [multi-column](https://github.com/mozilla/protocol/issues/233) content. We also have the [side bar menu](https://protocol.mozilla.org/patterns/organisms/sidebar-menu.html). I doubt we really need all of these things, but we should settle on some standardized container sizes. Hopefully that should suit most of our needs, and give us enough flexibility to create things like above, without needing lotf of molecules for each use case.

**Comment by stephaniehobson** [comment]
Sorry, I should be more clear with my requirements:S

1) Most of these use a h2 but the heading needs to be considerably smaller
2) The default bottom margin on a `p` is not enough to separate these elements, a larger bottom margin or perhaps a vertical line like the old style would be useful. (not needed if they are side by side)
3) Old style had smaller body text than regular body text but I'm not sure that's good.

**Comment by stephaniehobson** [comment]
I think #297 might solve 90% of this.

I'll code what I need into bedrock for now and it can be back ported or removed as appropriate.
