### ISSUE TITLE
Create standard container sizes

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#298]
We've been discussing how best to standardize container sizes in various issues and PRs:

- Component for multi-column content: https://github.com/mozilla/protocol/issues/233
- Option for narrower content: https://github.com/mozilla/protocol/issues/232
- Full blown grid system: https://github.com/mozilla/protocol/pull/244
- Narrow / compact version of the newsletter form: https://github.com/mozilla/protocol/issues/225
- ~Component for text content in sidebar: https://github.com/mozilla/protocol/issues/294~

These are all good ideas that have real use cases, and some of them may well have "legs". But I'm not sure we need all of them? If we had a set of standardized container classes, we may need fewer components and have overall more flexibility in creating new pages.

A set of container sizes could be concerned with just `width` or `max-width`, as opposed to layout or positioning. More complext layouts (such as cards) could still have their own layout classes, but simpler layouts could live within the realm of component or page CSS.

e.g.

- `mzp-l-content` (already exists)
- `mzp-l-content-half`
- `mzp-l-content-third`
- `mzp-l-content-quarter`

**Comment by stephaniehobson** [comment]
#294 doesn't need a container, it needs smaller headings and maybe a bottom margin.

**Comment by alexgibson** [comment]
> #294 doesn't need a container, it needs smaller headings and maybe a bottom margin. (The sidebar is the container)

Ah, I wasn't quite clear if it was suggesting a new component or not 👍

**Comment by craigcook** [comment]
This was done in https://github.com/mozilla/protocol/pull/595
