### ISSUE TITLE
Create new description atom

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#299]
Many existing components feature a common description at various places within their markup.

- `mzp-c-call-out-desc`
- `mzp-c-card-feature-desc`
- `mzp-c-hero-desc`
- `mzp-c-billboard-desc`
- `mzp-c-card-picto-desc`

They all look very similar, but we're styling them all at the component level.

![screen shot 2019-02-07 at 11 39 50](https://user-images.githubusercontent.com/400117/52409450-6c96df80-2acd-11e9-84f2-473f66103960.png)

![screenshot_2019-02-07 call out - protocol design system](https://user-images.githubusercontent.com/400117/52409458-73255700-2acd-11e9-8c0d-6e5f9295e185.png)

![screenshot_2019-02-07 cards - protocol design system](https://user-images.githubusercontent.com/400117/52409473-791b3800-2acd-11e9-9724-432cc01900ca.png)

This isn't terribly efficient, and it also means it's sometimes hard to do simple things, such as reorder the content within the Hero section (the button might come before the description for example, but the styles assume the description comes first).

It might be more flexible if we settled on a standard description atom, with a couple of different options related to font size, surrounding margin e.g.

- `mzp-u-desc`
- `mzp-u-desc-lg`

**Comment by stephaniehobson** [comment]
Maybe like #297 only with the `@include text-body-*` values?
