### ISSUE TITLE
Cursor pointer missing on navigation links without a hover menu

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#304]
If a navigation menu item does not have a `mzp-has-drop-down` or `mzp-js-expandable` class, then it acts like a regular link e.g.

```html
<li class="mzp-c-menu-category">
  <a class="mzp-c-menu-title" href="https://www.mozilla.org/firefox/">Firefox</a>
</li>
```

Whilst this works as intended, hovering over the link will not show the regular pointer cursor:

![menu-link](https://user-images.githubusercontent.com/400117/52554814-f0a7da80-2ddf-11e9-9f8f-1349fd652eab.gif)

This seems to be the offending line https://github.com/mozilla/protocol/blob/master/src/assets/sass/protocol/components/_menu.scss#L100

**Comment by stephaniehobson** [comment]
Fixed in #308
