### ISSUE TITLE
How do we include Sharp Sans in Protocol when we can't include it in the repo?

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#312]
Whatever license we end up having for Sharp Sans will not let us include it in this repo. So how do we include all the styles for it here?

**Proposal:**

In Protocol we create a font family stack that includes a generic key word like `brand-sans` that falls back to system fonts:

```
$font-brand-sans: brand-sans, system-font, X-LocaleSpecific, sans-serif;
```

And then in bedrock we create an import to define the `brand-sans` font-face. 

```
@import '../font/brand-sans';
```

Pros: 
- simple global include in bedrock to get brand font

Cons:
- fallback font will get font size, line height, etc defined for Sharp Sans.

**Comment by stephaniehobson** [comment]
Alternatively, it looks like we can over-ride variables in SCSS.

For this approach we would create a mixin that took configuration values for fonts:

```
$brand-available = false;

@mixin brand-sans($line-height, $weight) {
   @if $brand-available {
      font-family: system-font;
      line-height: $line-height ;
      font-weight: $bold;
  @else {
      font-family: system-font;
      line-height: $line-height *1.2;
      font-weight: $bold + 100;
   }
}

h1 {
    @include brand-sans(18px, 1.5, bold); 
}
```

In bedrock we would then over-rule the global variable:

```
@import '../font/brand-sans';
$brand-available = true;
```

Pros:
- Highly designed fallback for brand font.

Cons:
- This gets really really complicated if we want to define different font sizes for different break points.

**Comment by stephaniehobson** [comment]
I suppose we could try to simplify #2 with more abstracted versions of the mixin `@import brand-display-large();` for example.

**Comment by stephaniehobson** [comment]
Yes, that is the way to do it. I will re-write proposal 2 to reflect this. Only those of you who read email comments will ever see this 👋

**Comment by pmac** [comment]
I hope the designers realize what a nightmare they've caused us with this font choice 😠

**Comment by craigcook** [comment]
Really good idea. And as a minor nitpick, I don't know if we should name it `brand-sans` if only because it may not always be a sans-serif font. Maybe a generic name like just `brand-font` or `brand-font-display`(if it goes with a matching `brand-font-body`) ?

**Comment by stephaniehobson** [comment]
Then we also need to specify which brand. But that makes sense because we can't assume Mozilla will have a serif font forever either.

**Comment by craigcook** [comment]
> Then we also need to specify which brand. But that makes sense because we can't assume Mozilla will have a serif font forever either.

Oh, true... unless the variable gets redefined in a theme? But that sounds complicated. 

Maybe `brand-font-firefox` and `brand-font-mozilla`?

**Comment by stephaniehobson** [comment]
Sounds like we can go with the first and significantly easier solution!

**Comment by stephaniehobson** [comment]
Are we ever going to want to include both fonts on the same page? Maybe we could just define the brand font once at the top of the page rather than needing to theme it...

```
$font-brand: brand, system-font, X-LocaleSpecific, sans-serif;
```

```
@font-face {
  font-family: 'brand';
  src: url('zilla.woff');
}
```
Or 

```
@font-face {
  font-family: 'brand';
  src: url('sharpsans.woff');
}
```

**Comment by jgmize** [comment]
Closing this in favor of https://github.com/mozilla/protocol/issues/386
