### ISSUE TITLE
Consume protocol-colors design tokens

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#32]
We have a separate repo here for design tokens, but we don't yet seem to consume it in Protocol. Not quite sure where doing this fits in the roadmap, but my gut says the earlier we do this the easier it will be?

https://github.com/mozilla/protocol-design-tokens

**Comment by michaelmccombie** [comment]
I'm splitting consuming the design tokens in to separate issues because there is a fair amount of refactoring involved with each group (colors, assets, layout, type)

**Comment by alexgibson** [comment]
Colors is now combined in https://github.com/mozilla/protocol-tokens, so closing this.
