### ISSUE TITLE
Is it `.mzp-is-state` or just `.is-state`?

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#324]
We've been inconsistent team!

**Comment by stephaniehobson** [comment]
Things that use `.is-state`:
- Details
- Footer
- Menu
- Navigation

Things that use `.mzp-is-state`:
- Modal
- Sidebar menu
- Form errors

**Comment by craigcook** [comment]
Should be `.mzp-is-state` according to examples in https://protocol.mozilla.org/docs/naming.html

**Comment by alexgibson** [comment]
I would consider things using `.is-state` a bug, given that the docs suggest using the namespace 👍
