### ISSUE TITLE
Visited link colour in t-dark themes too dark

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#335]
It's still purple like the light theme 😢

<img width="594" alt="Screen Shot 2019-03-12 at 2 44 21 PM" src="https://user-images.githubusercontent.com/854701/54238320-5a95cb80-44d5-11e9-9e6d-e0f2838956ba.png">

**Comment by craigcook** [comment]
There is a [`light-links` mixin](https://github.com/mozilla/protocol/blob/master/src/assets/sass/protocol/includes/_mixins.scss#L230) that we could include with any dark themes, but it just makes all links white and doesn't distinguish visited and unvisited. We could probably improve on that.
