### ISSUE TITLE
Add a reference sketch file to Protocol's readme

### ISSUE THREAD

**Issue by johngruen** [mozilla/protocol#338]
In order to move forward on rolling out new brand work, we'll need a canonical reference from which to work. While this file should probably have a different home eventually, we can start by adding a file to the repo for reference.

This file should include: 
- [ ] color values annotated with intended usages
- [ ] grid values annotated with intended usages
- [ ] link designs annotated with intended usage
- [x] button designs annotated with intended usages
- [ ] basic type scale and font face designs for headers, paragraphs etc
- [ ] basic permutations of a feature-component (replacement for hero) showing usage of all above

**Comment by johngruen** [comment]
This file should include the following: 
- [ ] color values annotated with intended usages
- [ ] grid values annotated with intended usages
- [ ] link designs
- [ ] button designs annotated with intended usages
- [ ] basic type scale and font face designs for headers, paragraphs etc
- [ ] basic permutations of a feature-component (replacement for hero) showing usage of all above

**Comment by johngruen** [comment]
Note: this is probably a blocker for all of the other updates to protocol

**Comment by ejregithub** [comment]
Need the link to the one Vince created for buttons.
