### ISSUE TITLE
Implement New Brand Color Tokens

### ISSUE THREAD

**Issue by johngruen** [mozilla/protocol#339]
I believe @vincejoyiv has these colors locked down. We should go ahead and update tokens to match new colors.

**Comment by stephaniehobson** [comment]
Updated colour tokens have been published we just need to pull them in \o/

https://github.com/mozilla/protocol-tokens/pull/34

**Comment by stephaniehobson** [comment]
Oop, looks like we need a new npm package published first. 

cc: @michaelmccombie
