### ISSUE TITLE
Implement Updated Font Stacks

### ISSUE THREAD

**Issue by johngruen** [mozilla/protocol#342]
We need to define font-family rule sets for: 
* headers
* body text
at least

**Comment by stephaniehobson** [comment]
Recommended next steps:
1) create a Zilla theme
2) remove Zilla from the default font stack
3) make the default font for Protocol system fonts
4) update the Firefox theme to use Sharp Sans and Inter

@vincejoyiv @michaelmccombie Does this make sense or should we make the default for all text  Inter?

**Comment by stephaniehobson** [comment]
See also #312

**Comment by johngruen** [comment]
For Mozilla: 
* Zilla Slab for headlines

For Firefox:
* Sharp Sans for headlines

For community:
* Inter for headlines

all: 
inter for body

**Comment by stephaniehobson** [comment]
Steps 1 and 2 can happen.

Steps 3 and 4 are blocked by:
- [ ] New font files were supposed to be coming from Sharp. Did we receive them? Are they on the server?
- [ ] What is the new type scale?

**Comment by stephaniehobson** [comment]
I have the new font files, need to get them on a server.

**Comment by stephaniehobson** [comment]
With a little help from @metadave the fonts are now on a server and ready to use.

And new typescale can be found here: https://github.com/mozilla/protocol-sketch-plugin/blob/master/src/data/firefox/text.json
