### ISSUE TITLE
Implement Updated Link Rules

### ISSUE THREAD

**Issue by johngruen** [mozilla/protocol#343]
we need to make sure we cover the following:
* link color for all states
* link outline for all states (if any)
* link underline for all states (if any)
* additional treatments for internal vs external links

States:
* default
* hover
* focus
* visited
* hover a visited link
* focus a visited link

**Comment by stephaniehobson** [comment]
Do we want active states?

**Comment by stephaniehobson** [comment]
For light and dark themes please!
