### ISSUE TITLE
Add a content component that applies baseline styles for standard elements

### ISSUE THREAD

**Issue by johngruen** [mozilla/protocol#355]
For large chunks of semantically formatted content (for example markdown) we need a class to apply to a parent element that will make default elements have defaults.

**Comment by stephaniehobson** [comment]
Example: Lists are reset to not have bullet points, but in regular text content we want them to have bullets without having to apply a class to each list.

**Comment by stephaniehobson** [comment]
See also #293

**Comment by stephaniehobson** [comment]
Things to include:

- list styling (mzp-u-list-styled)
- table styling (mzp-u-data-table)
- stepped down headings, like in the article component
  - I think we should de-couple these styles from the article component
