### ISSUE TITLE
"We no longer use black type"

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#372]
Need a bit of clarification from the designers on this but it sounds like we need to make the default text colour `$color-off-black`

**Comment by stephaniehobson** [comment]
Just for the Firefox theme, still need to keep black for Mozilla themed pages.

**Comment by stephaniehobson** [comment]
Which opens the question... what do we do with the navigation menu?

**Comment by alexgibson** [comment]
We have several page designs circulating currently that feature `$color-off-black` (`#20123a`) as the new type color. This is already rolling into bedrock on a page by page basis, but it's not formally documented anywhere in Protocol. It's a small detail, but doing it like this is on a page by page basis is going to incur tech debt to go and clean up later. It would be much easier to roll this into a Protocol update.

@dzingeek can you please help define this? We lack clarity on the open questions @stephaniehobson makes above, so right now we're just guessing what the rules are. Thanks
