### ISSUE TITLE
Update product button theme color

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#380]
As per [this discussion](https://github.com/mozilla/bedrock/issues/7129#issuecomment-489210613), we need to update the product button theme color in Protocol so that it works better against dark backgrounds for the upcoming trailhead campaign.

Old color: `#0250bb` `$color-blue-60`
New color: `#0060df` `$color-blue-50`

/cc @dzingeek

**Comment by dzingeek** [comment]
**Just a note:** this isn't just for the trailhead campaign but for the new brand look and feel.

**Comment by stephaniehobson** [comment]
Should we bump the hover colour one brighter too?
