### ISSUE TITLE
Create notification bar component

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#383]
The upcoming Trailhead designs show a new notification both on /thanks and on /whatsnew

![image](https://user-images.githubusercontent.com/400117/57518128-496c0e00-7310-11e9-811f-081fccbf4f70.png)

It also appears in our new brand guidelines:

<img width="547" alt="Screenshot 2019-05-10 at 10 43 17" src="https://user-images.githubusercontent.com/400117/57518231-7ddfca00-7310-11e9-9197-64dbe0a54c45.png">

Things to note:

- There are a range of new colors here that are not currently in our tokens.
- The bar seems like it needs to support an optional button to close the notification.

---
Estimates |  |
--- | --- |
Eng | 5 |

**Comment by ejregithub** [comment]
@amychurchwell - please size this work, apply the Estimate and tag it with the Priority, P1, P2, P3 assigned by Justin.

**Comment by amychurchwell** [comment]
@hoosteeno what priority would we give this task? I was considering it P2(?) because it is a piece of the work in https://github.com/mozilla/bedrock/issues/7468 which is marked as P1

**Comment by hoosteeno** [comment]
This is P1.

**Comment by craigcook** [comment]
Since it ties to WNP69 I think it inherits the P1 from that epic.

**Comment by johngruen** [comment]
@amychurchwell let's move this into the the current sprint!
