### ISSUE TITLE
Add emphasis box component

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#385]
This box with shadow and padding is showing up in designs enough that we should make it a 
component:

<img width="720" alt="Screen Shot 2019-05-23 at 1 08 50 PM" src="https://user-images.githubusercontent.com/854701/58283704-d2963280-7d5d-11e9-8db6-aed8845a7555.png">

<img width="724" alt="Screen Shot 2019-05-23 at 1 22 49 PM" src="https://user-images.githubusercontent.com/854701/58283715-e0e44e80-7d5d-11e9-8e43-809e716fd25e.png">

**Comment by stephaniehobson** [comment]
See also mozilla/protocol-tokens#51

**Comment by johngruen** [comment]
is there a measurement spec for this or just a static image?

**Comment by amychurchwell** [comment]
@johngruen design linked in bedrock issue for page containing this component, also static image- https://github.com/mozilla/bedrock/issues/7354#issuecomment-511815158 Should we track down sketch file? I personally feel that we have solid direction for the dev work here.
