### ISSUE TITLE
js:uglify and css:clean Gulp tasks do not work

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#39]
- Both the `js:uglify` and `css:clean` gulp tasks are currently misconfigured and fail silently.

**Comment by michaelmccombie** [comment]
I resolved the css:clean issue and included it as a commit https://github.com/mozilla/protocol/pull/40/commits/18fcab4d3e333e697a5f392b31d949d71e70ca93 in this branch https://github.com/mozilla/protocol/pull/40

Uglify is something that we wanted to discuss at some point https://github.com/mozilla/protocol/issues/25 . We can either remove it now or fix the bug by editing the path names as shown below.

<img width="457" alt="screen shot 2018-04-17 at 6 04 25 pm" src="https://user-images.githubusercontent.com/5924575/38906175-dded2a06-4269-11e8-9559-6d0da35d1434.png">
