### ISSUE TITLE
Add component for 'feature' lists.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/protocol#394]
Currently protocol supports [information lists](https://protocol.mozilla.org/patterns/atoms/typographic.html#list-elements) but we often design pages with lists of headlines, descriptions, and images. We should include this in the design system.

This could potentially be a [picto card](https://protocol.mozilla.org/patterns/molecules/picto-card.html) variation?

<img width="611" alt="Screen Shot 2019-06-27 at 3 37 20 PM" src="https://user-images.githubusercontent.com/30483988/60305521-a38d5680-98f1-11e9-8179-12c2b923a9f4.png">

**Comment by amychurchwell** [comment]
Adding a design label because I think a designer should weigh in if this is the visual direction we should move forward with?

**Comment by alexgibson** [comment]
I’m not 100% sure if we need a new component for this? Like you point out, this is almost a [compact version of the Picto Card](https://protocol.mozilla.org/patterns/molecules/picto-card.html#picto-card-compact), just with a couple of minor differences like icon size etc.

If we did create a new component for this, we should decommission the existing Picto Card and update all the existing instances to use the new component.

**Comment by alexgibson** [comment]
See also: https://github.com/mozilla/protocol/issues/382

**Comment by amychurchwell** [comment]
@alexgibson I think you are right! I'm going to consider this a dupe issue & close. We should probably just tweak the picto card, as mentioned.
