### ISSUE TITLE
Update Firefox theme text colors

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#405]
Once the color tokens have been updated in https://github.com/mozilla/protocol-tokens/pull/37, the Firefox theme should use `#42425a` as the base text color and `#20133a` for headings.

**Comment by wboucherfischer** [comment]
Please update to include this on https://protocol.mozilla.org/fundamentals/color.html to show as 'Display Font Primary Colors'.

See: https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit?usp=sharing

**Comment by johngruen** [comment]
#447
