### ISSUE TITLE
Protocol Fx: Update Typography page to include Metropolis Font

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#411]
Update https://protocol.mozilla.org/fundamentals/typography.html to have Metropolis replace Zilla Slab as the Heading Font. Weights used are Normal and Bold.

See: https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit?usp=sharing

**Comment by craigcook** [comment]
https://github.com/mozilla/protocol/pull/403
