### ISSUE TITLE
Protocol FX: Update Heading elements to Metropolis

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#412]
On https://protocol.mozilla.org/patterns/atoms/typographic.html

- Update Heading Elements to reflect Metropolis and not Inter. 

See: https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit?usp=sharing

**Comment by craigcook** [comment]
https://github.com/mozilla/protocol/pull/403
