### ISSUE TITLE
Protocol Fx: Explain how to use Firefox Theme on https://protocol.mozilla.org/fundamentals/themes.html

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#414]
Add and explain the firefox theme on https://protocol.mozilla.org/fundamentals/themes.html

**Comment by stephaniehobson** [comment]
Maybe you could elaborate on what the current page is missing? https://protocol.mozilla.org/fundamentals/themes.html

**Comment by wboucherfischer** [comment]
My bad. I added more information to the issue.
