### ISSUE TITLE
Protocol Fx: Add custom paragraph text sizes

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#418]
see: https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit?usp=sharing
 For https://protocol.mozilla.org/patterns/atoms/typographic.html: 

Add:

Requirement | Description
-- | --
Body LG | Inter, 18px, 1.125 rem
Body MD | Inter, 16px, 1 rem
Body SM | Inter, 14px, .875 rem
Body XS | Inter, 12px, .75 rem

**Comment by craigcook** [comment]
This falls under the global type scale(s) #410
