### ISSUE TITLE
Protocol Fx: Add custom sizes for Lists

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#419]
On https://protocol.mozilla.org/patterns/atoms/typographic.html

For Text, add custom sizing for lists:

Requirement | Description
-- | --
List LG | Inter, 18px, 1.125 rem
List MD | Inter, 16px, 1 rem
List SM | Inter, 14px, .875 rem
List XS | Inter, 12px, .75 rem

See: https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit?usp=sharing

**Comment by stephaniehobson** [comment]
Lists always inherit the body font size. Do we have a use case for lists being a different size from the body copy?

**Comment by wboucherfischer** [comment]
I'm trying to include all the sizes we have for body copy from the Brand guidelines. This should probably be merged with the custom paragraph text issues.

**Comment by craigcook** [comment]
This falls under the global type scale(s) #410
