### ISSUE TITLE
Protocol FX: Add custom link sizes

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#420]
To https://protocol.mozilla.org/patterns/atoms/links.html
add the following sizes for Dark Links and Light links. 
Link Size: X-small | X-Small sized link, 12px
-- | --
Link Size: Small | Small sized link, 14px
Link Size: Medium | Medium sized link, 16px
Link Size: Large | Large sized link, 18px
 
See: https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit?usp=sharing

**Comment by craigcook** [comment]
I don't think we need to define sizes specifically for links, regular text links get their size from their parent.

**Comment by wboucherfischer** [comment]
how about in areas where we have a stand alone link like this?

[image: Download Firefox — Free Web Browser — Mozilla(1).png]
