### ISSUE TITLE
Figure out our approach to line-height for headings

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#421]
At one time all our display text sizes had a line-height rounded to the nearest multiple of four, intended to align to a 4px baseline grid. That was recently simplified so they just use a 1.1 line-height and no rounding. Since then the brand guidelines were revised and once again prescribe a 4px baseline grid. Protocol and the brand guide are now out of sync and we should decide what to do:

1. Add the rounding back to the sizing mixins, so Protocol will match the brand guide.
2. Change the brand guide to remove the rounding, so the brand guide will match Protocol.
3. Stick with a simple 1.1 line-height in Protocol, so Protocol will differ from the brand guide. If we commit to this we should document it, with a justification for the difference.

**Comment by wboucherfischer** [comment]
@jrouse can you take a look. I'm fine with the 1.1 line-height if that is what we were using. I think the designers and the brand people want the rounding. I think we need some discovery and consensus around the 1.1 rem line-height.

**Comment by craigcook** [comment]
After some discussion it was decided to update Protocol to follow the brand guidelines, so we're adjusting the line-heights at each heading size to round them to a multiple of 4 (or close to it).

But with that settled, the Firefox brand and Mozilla brand each have completely different type scales. So we need to either consolidate to a single type scale for all brands (and update the brand guides accordingly) or figure out how to implement different type scales in different themes in Protocol. 

But we've at least decided to let the brand guide lead and Protocol will follow, so I'm calling this specific issue closed.
