### ISSUE TITLE
Protocol FX: Add pattern to links to show light links

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#427]
Add to: 
https://protocol.mozilla.org/patterns/atoms/links.html

Do this for normal links and light links. The think on this is that there are lines that we just use as links and we use different sizes across the website. 

see: 
https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit

Include states for visited, unvisited, hover, active, normal. 

Currently we don't have light options for visited, and active.

**Comment by craigcook** [comment]
I think this entails a few different things...

1) We should work on standardizing a dark theme, which now that we're doing multiple brand themes could be considered a child of each brand theme... like there would be a default "Firefox theme" extended with "Firefox theme - dark".

2) Expand on our ["light links" mixin](https://github.com/mozilla/protocol/blob/master/src/assets/sass/protocol/includes/_mixins.scss#L230), but then it might need to change for different dark themes so a single mixin might not work, unless we use custom properties... hmm.

**Comment by ehot** [comment]
<img width="508" alt="Screen Shot 2023-02-24 at 11 06 29 AM" src="https://user-images.githubusercontent.com/2040610/221242446-47c548e0-5857-4bc6-b836-ab534bee9b45.png">
<img width="767" alt="Screen Shot 2023-02-24 at 11 06 35 AM" src="https://user-images.githubusercontent.com/2040610/221242454-9c52d879-7afa-43a6-b991-0d5a0644e837.png">

**Comment by craigcook** [comment]
We'll sweep this up with improved dark themes. https://github.com/mozilla/protocol/issues/853
