### ISSUE TITLE
Inline link style and specs for fx 

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#428]
Add link colors to https://protocol.mozilla.org/patterns/atoms/links.html and https://protocol.mozilla.org/fundamentals/color.html

See: [](https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit?usp=sharing)

Hex | Usage 
-- | --
#0060DF | Unvisited link color, light background
#B833E1 | Visited link color, light background
#EDEDF0 | Active link background color, light background
#FFFFFF | Unvisited link color, dark background
#EDEDF0 or #F6B8FF | Visited link color, dark background
#FFFFFF, 20% opacity | Active Link background, dark background

**Comment by stephaniehobson** [comment]
I think it would be better if we added the token names rather than the hex values.

`$color-link`
`$color-link-hover`
`$color-link-visited`
`$color-link-visited-hover`

And we should create tokens for the dark colour scheme. Right now it uses white.

**Comment by johngruen** [comment]
please add that `:visited` should only be set if the `mzp-t-usage-presentation` theme is set on the body element (per #447 )

**Comment by stephaniehobson** [comment]
@dzingeek Do the CTA colour changes in https://github.com/mozilla/protocol/issues/589 have any implication for link colours?

**Comment by dzingeek** [comment]
great question @stephaniehobson right now i don't think so but we should take a look at these now that we have some background colors decided.

**Comment by dzingeek** [comment]
Here are updated specs for inline links to match (as much as we can) the cta text links and button styles/colors
![Fx Inline-links](https://user-images.githubusercontent.com/3740746/83427327-6a087980-a3e5-11ea-9d85-e166c373a402.png)

**Comment by craigcook** [comment]
This will be part of theming
