### ISSUE TITLE
Add Firefox themed buttons

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#429]
See: https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit?usp=sharing

![components-buttons](https://user-images.githubusercontent.com/50332473/61408771-abf40400-a895-11e9-87e6-f92913f82243.png)

Buttons comes in 4 sizes | Small, Medium, Large and Extra Large.
-- | --
Buttons have 5 states | Default, Hover, Pressed, Focus and Disabled.
Buttons are accessible | Color Contrast, Typography, Interaction
There is a primary action button | This button is used as a primary call to action.
The primary button can be used on both light and dark backgrounds. | The primary button can be used on both light and dark backgrounds.
There is an inverted Secondary button. | This can be used on a light background.
There is an inverted Secondary Button that goes over a dark background. | This is used as an alternative for a button over a dark background.

**Comment by justinkropp** [comment]
@craigcook The button styles have been updated to reflect consensus between myself, @dzingeek and Stephen Horlander. I'll update the table above, but below are the new visual specs. Dark theme is forthcoming.

----

## Primary
![Buttons - Primary](https://user-images.githubusercontent.com/1461798/67957675-589b8c80-fbcc-11e9-8944-49fa66fd1c19.png)

## Secondary
![Buttons - Secondary](https://user-images.githubusercontent.com/1461798/67957674-589b8c80-fbcc-11e9-9bdd-98e44ac8cd53.png)

## Neutral
![Buttons - Neutral](https://user-images.githubusercontent.com/1461798/67957673-589b8c80-fbcc-11e9-940c-a59f3c84f3bb.png)

**Comment by stephaniehobson** [comment]
@justinkropp Can you please let me know what font size the buttons should be using? When I measure it it's `15px` but making the font smaller in the CTAs felt odd and that doesn't match anything that's in our type scale. But when I use the standard 16px it looks odd too.

**Comment by justinkropp** [comment]
@stephaniehobson Thanks for asking. The sizing is as follows (see attached for reference as well):

- sm = 12px
- md = 14px
- lg & xl = 16px

<img width="654" alt="Screen Shot 2020-04-02 at 10 21 58 AM" src="https://user-images.githubusercontent.com/1461798/78260985-a34b6880-74cc-11ea-9df8-1921694f59b9.png">
