### ISSUE TITLE
Add Firefox themed select drop down [forms]

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#435]
Protocol Fx: Add dropdown to https://protocol.mozilla.org/patterns/atoms/forms.html for Fx theme

![dropdown](https://user-images.githubusercontent.com/50332473/61561138-02db1400-aa23-11e9-8981-7b643e605b0a.png)

Dropdown, normal | Default
-- | --
Dropdown, Hover | Hover over dropdown
Dropdown, Focus | Focus selection when dropdown is selected
Dropdown, focus, menu | Dropdown with focus selection, menu is activated
Dropdown, menu, divider line | In the menu, there is a divider line to allow spatial division between Menu List items.
Dropdown, Disabled | Disabled state
Dropdown, success | There is a success validation state for the dropdown.
Dropdown, error | There is an error validation state for the dropdown when it contains an error.

See: https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit?usp=sharing

**Comment by craigcook** [comment]
Dropdowns are notoriously difficult to style consistently across browsers. The suggested design above may not be cleanly achievable and we need to do some testing.

**Comment by johngruen** [comment]
So here's my put on all inputs
...yes they are fussy to stylize, but i do think we should build out components for custom-designed versions available in Protocol. we can gracefully degrade them, or make the classes optional

**Comment by wboucherfischer** [comment]
@johngruen we have discussed this with Dev and have decided to explore this. They are open to it, it's jsut a matter that it's done correctly in an accessible way with good loading performance.

**Comment by dzingeek** [comment]
updated designs (based off of input field designs) + specs 
![dropdown-menu](https://user-images.githubusercontent.com/3740746/67815209-8b764100-fa63-11e9-91fc-f5fc78874f0c.png)
![dropdown-menu-specs](https://user-images.githubusercontent.com/3740746/67815211-8c0ed780-fa63-11e9-9a0c-54506fde2de8.png)
