### ISSUE TITLE
Create switch form input

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#436]
Add switch to https://protocol.mozilla.org/patterns/atoms/forms.html for Fx Theme

Switch animation between on/off | Switch animation between on/off
-- | --
Switch, Off | Default state
Switch, On | Shows color selection that the switch is on
Switch, Disabled | Disabled State
Switch, On, Focus | Focus selection on on-switch
Switch, Off, Focus | Focus selection on off-switch
Switch, Error | Error notification
Switch, Success | Success Notification

See: https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit?usp=sharing

We also need to add a switch to Mozilla theme with same requirements.

**Comment by craigcook** [comment]
Switch inputs don't exist in HTML, they're produced by hiding a checkbox and generating a custom widget on top of it. There's some trickery involved and it can be hard to get it consistent across browsers. We need to look into this and take a careful approach.

We should also work up a use case for this to determine its necessity and priority.

**Comment by wboucherfischer** [comment]
I think it would be easier to switch between themes and have a toggle, or
somehow have separate virtual destinations for Mozilla theme vs. Fx theme.
If we mix the two it's going to get confusing awfully fast.

**Comment by techieshark** [comment]
> We should also work up a use case for this to determine its necessity and priority.

The Material UI [switch component page](https://material-ui.com/components/switches/) describes when to use a switch (in that system) by linking to [this article](https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8) which differentiates between a checkbox for selecting state and a switch for also immediate executing: 

> Tapping a toggle switch is a two-step action: selection and execution, whereas checkbox is just selection of an option and its execution usually requires another control.

I guess the thinking is that humans are used to switching leading to immediate changes, whereas the real-world analogy of a checkbox is on a paper form where ticking the box in that context obviously doesn't lead to any immediate change. (That said, perhaps over time the paper analogy seems less relevant?)

**Comment by stephaniehobson** [comment]
Oh the immediate change vs change and submit makes the a11y recommendations I've seen make more sense.

They seem to favour a[ button instead of a checkbox](https://scottaohara.github.io/a11y_styled_form_controls/src/toggle-button-switch/) approach. Which does make more sense if it's triggering some script to be executed immediately.

The button approach also makes it kind of awkward to use in an actual form context since you can't submit button state information with a form action (I don't think?).

**Comment by alexgibson** [comment]
Do we have a practical use-case on mozorg where a switch would make more sense as opposed to a checkbox or radio input? I’m struggling to find one.
