### ISSUE TITLE
Add custom styled radio buttons and checkboxes [forms]

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#439]
Protocol Fx: Update and add Fx theme for Radio buttons and Checkboxes at https://protocol.mozilla.org/patterns/atoms/forms.html

See: https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit?usp=sharing

Checkbox, unselected | Default
-- | --
Checkbox, selected | Shows a checkmark populated in checkbox upon selection
Checkbox, Hover, Unselected | Shows a green outline upon hover
Checkbox, Hover, Selected | Shows a green outline upon hover and shows checkmark populated in box.
Checkbox, Focus, Unselected |  
Checkbox, Focus, Selected |  
Checkbox, Disabled, Selected |  
Checkbox, Disabled, Selected. |  
Radio Button, unselected | Unselected Radio button
Radio Button, Selected | Shows a dot upon selection
Radio Button, Hover, Unselected |  
Radio Button, Focus, Selected | Green outline around radio button showing selection
Radio Button, disabled, unselected | Disabled radio button
Radio Button, Disabled, Selected | Radio button that is selected and disabled.

**Comment by craigcook** [comment]
Like some other form controls, radio buttons and checkboxes aren't easily styled in a browser (they're usually rendered by the OS). The only reliable way to style these is actually to hide them and replace them with something else, an image or some browser-rendered element. That's doable but fiddly, with some compatibility and accessibility concerns.

**Comment by stephaniehobson** [comment]
Yeah, for maintenance and accessibility reasons it's best to stick with the browser defaults on websites.

It would be great if we had direction about how to style different groupings and their labels though.

For example we want to treat a single checkbox to agree to the privacy policy different from a group of check boxes with a heading.

**Comment by wboucherfischer** [comment]
1) Can you point me to the research on the browser defaults. More and more websites are using stylized radio buttons and checkboxes. I've never seen an issue on the accessibility standpoint on websites I've worked on before. The main issue I've seen has always been the worry about the performance hit. 

2) The designers would really like styled checkboxes and radio buttons. It's a way to make the checkboxes and radio buttons in line with the aesthetic of the design system and an extension of the brand. It's also a way to improve the readibility and usability since the default sizing tends to be rather small. 

3) We are inconsistent on the use of the checkboxes already on the website.  Firefox Monitor uses a stylized checkbox. 
![Download Firefox — Free Web Browser — Mozilla(1)](https://user-images.githubusercontent.com/50332473/61737949-1d243300-ad3e-11e9-937f-bd5c50f1b444.png)

**Comment by craigcook** [comment]
It's not impossible, it's just fiddly, and if we do it we need to do it right so they remain accessible and so they still function in old browsers.

Monitor isn't using Protocol, and their implementation of those custom checkboxes isn't very accessible. 

- They're excluded from the tab order so there's no way to change my selection with a keyboard, you have to use a pointing device. 
- They do have labels but no `for` attributes, they're just relying on implicit association. That doesn't work in some older browsers so the labels won't always be clickable.
- I haven't tested with a screen-reader but the lack of keyboard focus tells me maybe they might not be read properly as form controls. 
- They're not actually checkboxes at all, they're radio buttons, but they've been styled to look like checkboxes, which is really confusing and misleading.

So in the end this is actually a good example of a bad way to do it. Maybe we can help them.

Additionally, and this is more about how the entire site is built and not just how these controls are implemented, but there is no form and no submit button for those radios, it's a pure JavaScript simulation of a form. The radio buttons also have no values, so even if it was a form and it had a submit button there would be no value saved. There's no way to change one's email preference if JavaScript fails. But nothing on the site works at all without flawless JS so this nonfunctional fake form is moot anyway.

**Comment by wboucherfischer** [comment]
So I've talked to the design team and this is something we'd really like to have - stylized radio buttons, checkboxes and dropboxes. It gives us greater control over the usability and readibility and the sizing of the controls, it allows us to create a comprehensive design system with typography that is representative of the brand and an extension of the brand. It would also allow us to design and create controls and have one system/one vision that everybody across the Mozilla ecosystem would use rather than a rogue group creating their own version of a checkbox, radio button or dropdown. The controls would be accessible and cross browser compatible. 

I think this is a given.

**Comment by johngruen** [comment]
Agree that we should do this, but it's not mission critical at the moment...

**Comment by wboucherfischer** [comment]
We have discussed this with dev, they are open to it and exploring an accessible and stylized radio button and checkbox. I am concerned about inconsistency across the website in regards to checkboxes and radio buttons. On the monitor.firefox.com site, under monitor preferences, we have Checkboxes acting like radio buttons, and nothing matches the website in color, as we don't use purple as a control accent color. We'd like to get defined consistent interaction patterns and look/feel across all the controls. Also, I believe @craigcook  looked at the code for the checkbox like radio button and said it wasn't accessible. At the end of the day the goal is to have a common CSS framework for all controls across the website so there is a consistent interaction and look/feel. 

![Screen Shot 2019-08-01 at 9 10 57 AM](https://user-images.githubusercontent.com/50332473/62309683-d7055880-b43c-11e9-9dae-41230a2b5c56.png)

**Comment by dzingeek** [comment]
Update designs (based off of input field designs) and specs

![radio-button-specs](https://user-images.githubusercontent.com/3740746/67815274-bb254900-fa63-11e9-9c0a-710ffb298249.png)

![radio-buttons](https://user-images.githubusercontent.com/3740746/67815275-bbbddf80-fa63-11e9-9411-9a157ee34690.png)

**Comment by dzingeek** [comment]
Also adding the check boxes 

![checkbox](https://user-images.githubusercontent.com/3740746/67815322-dee88f00-fa63-11e9-8e87-a970f64e8635.png)
![checkbox-specs](https://user-images.githubusercontent.com/3740746/67815326-e019bc00-fa63-11e9-923a-4a12d20ffaec.png)

**Comment by dzingeek** [comment]
here are updated specs that include an error state

![checkbox-specs](https://user-images.githubusercontent.com/3740746/69283950-4ba60380-0ba2-11ea-97e6-c40df1853ac1.png)
