### ISSUE TITLE
Remove deprecated components?

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#44]
There are a couple of components in Protocol that we're likely placeholder, and are marked as deprecated. 

https://mozilla-protocol.netlify.com/patterns/atoms/buttons.html
https://mozilla-protocol.netlify.com/patterns/molecules/card.html

Now that we're beginning to pull in external dependencies like `protocol-colors` etc, which will likely require some refactoring, does it make sense to remove these deprecated elements now?

**Comment by michaelmccombie** [comment]
Removing them now seems reasonable to me. Unless @craigcook you have any thoughts.

**Comment by craigcook** [comment]
Those were basically just placeholders and examples while setting up the site. I agree, now that we're starting to add real content we shouldn't mix in misleading, deprecated stuff.
