### ISSUE TITLE
Add animation to notification bar component

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/protocol#440]
## Description

![image](https://user-images.githubusercontent.com/30483988/61663901-7d579e00-ac86-11e9-99af-5700f5cb7655.png)

The notification bar incoming in #431 has an option to be absolutely positioned and sticky on the page. In the event of multiple sticky notifications I think we should support an animated UX "stacking" behavior: 

![notifications](https://user-images.githubusercontent.com/30483988/61664938-b85ad100-ac88-11e9-97c5-35f2e9122785.gif)

_Note: I think we can all agree there should never be enough notifications to block a user's view like in this example. 😅_

**Comment by craigcook** [comment]
See also: https://github.com/mozilla/protocol/issues/251

We've talked for a long time about standardizing some animation effects, it just hasn't been a priority. We do have a handful of predefined transitions already but haven't put them to much use so far. [Photon has some basic guidelines](https://design.firefox.com/photon/motion/principles.html) we could start from.

**Comment by johngruen** [comment]
I don't think the toast/multi-notification thing is a priority, but having an animation here makes sense.

**Comment by johngruen** [comment]
Agree with craig that we can start from the photon library for animations here, but let's de-scope the idea of a toast stream

**Comment by craigcook** [comment]
We can consider this along with a broader approach to animation. https://github.com/mozilla/protocol/issues/251
