### ISSUE TITLE
Long declaration required to add icons to compact picto cards

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#443]
To add an icon to the picto cards the current syntax is:

```
.t-instance.mzp-c-card-picto.mzp-c-card-picto-compact .mzp-c-card-picto-content::before {
    background: ...;
}
```

We should be able to reduce the specificity so it can be referenced like:
```
.t-instance .mzp-c-card-picto-content::before {
    background: ...;
}
```
or even
```
.t-instance::before {
    background: ...;
}
```

**Comment by stephaniehobson** [comment]
We can achieve this in two ways:
1) Removing the background declaration from the mzp-c-card-picto-content:before
2) Moving the background declaration outside of the nesting.

I prefer #1. If we want to keep the background for demo purposes that style could be moved into demo specific styles sheets for the picto component.

**Comment by johngruen** [comment]
what is `.t-instance` doing here?

**Comment by stephaniehobson** [comment]
In bedrock when we add classes we do not add namespace. In this case the class was necessary to target this specific picto card instance. I didn't use that name in bedrock though, I just renamed it for the example here to try (and fail apparently) to communicate that an extra class has to be added.

The actual code from bedrock is:
```
.t-speak-up.mzp-c-card-picto.mzp-c-card-picto-compact .mzp-c-card-picto-content::before {
    background: url('/media/img/firefox/developer/icon-speak.svg') no-repeat;
}

.t-get-involved.mzp-c-card-picto.mzp-c-card-picto-compact .mzp-c-card-picto-content::before {
    background: url('/media/img/firefox/developer/icon-involved.svg') no-repeat;
}
```

**Comment by craigcook** [comment]
Closing this since we've added a new Picto component that deprecates the old Picto Card. The new Picto takes an inline image instead of a CSS background image, so it doesn't have this problem. And while the Picto Card is still in Protocol for now, it's slated for future removal and shouldn't get any more updates.
