### ISSUE TITLE
Seperate newsletter form and newsletter layout styling

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#444]
The form with the submission fields, error messages, and thank you should be able to be nested inside other containers. Right now it only works inside a `mzp-c-newsletter` container which comes with a bunch of layout styles that are unwanted in the current design I'm currently programming.

This might actually be a typo. I think we can just change line 7 of _newsletter-form.scss from `.mzp-c-newsletter ` to `.mzp-c-newsletter-form`

**Comment by johngruen** [comment]
are there UX deps here or is this just a code cleanup issue?

**Comment by stephaniehobson** [comment]
Just code cleanup.
