### ISSUE TITLE
Update Sketch library and created create symbols

### ISSUE THREAD

**Issue by ejregithub** [mozilla/protocol#446]
## Description

A task associated with the original issue "[Create issues on Protocol for missing components](https://github.com/mozilla/bedrock/issues/7444)" is being pulled out as separate issue, namely to fulfill the Success Criteria for "Sketch library and symbols created"

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Sketch library and symbols created

#### Tasks
- [ ] Add to Sketch library and create symbols

**Comment by ejregithub** [comment]
@wboucherfischer - please apply a sizing Estimate (Fibonacci scale) for the work required to complete this.

**Comment by craigcook** [comment]
We've switched to Figma. Sketch is Dead. Long Live [Design Tool].
