### ISSUE TITLE
Investigate Storybook for visual unit tests

### ISSUE THREAD

**Issue by johngruen** [mozilla/protocol#450]
We've used Storybook with great results on Firefox Accounts payments pages. The TL;DR with Storybook is that lets you create visual reference of real components and easily add as many permutations as you like by programmatically specifying variants.

Here's the Storybooks server we've stood up on [FxA Payments](http://mozilla.github.io/fxa/fxa-payments-server/?path=/story/components-alertbar--basic). Storybook documentation is [here](https://storybook.js.org/docs/guides/guide-html/).

**Comment by johngruen** [comment]
probably this is not necessary since the tool is quite similar to drizzle, so this is back-loggable. Just wanted to call it out

**Comment by craigcook** [comment]
We looked into Storybook as an alternative to Drizzle, but ultimately decided to go with Fractal as our new doc platform.
