### ISSUE TITLE
Add tokens for box-shadows

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#456]
There are 5 attributes that contribute a shadow element
- inset (boolean)
- color
- blur
- x
- y
- spread

**Expected CSS output**
```
$shadow-full: box-shadow: 0 8px 24px rgba(0, 0, 0, .1);
$shadow-half: box-shadow: 0 4px 12px rgba(0, 0, 0, .1);
```

**Expected JSON output (for Sketch consumption)**
```
{
    "inset": false,
    "color": '#0000001A',
    "blur":  24,
    "x": 0,
    "y": 8,
    "spread": 0
},
{
    "inset": false,
    "color": '#0000001A',
    "blur":  12,
    "x": 0,
    "y": 4,
    "spread": 0
}
```

**Comment by justinkropp** [comment]
After discussion with @craigcook @dzingeek and Stephen Horlander, a proposed update to the box-shadow property is as follows.

Four proposed _elevations_:

`.elevation-00 {
  border: 1px solid rgba(21,20,26,0.24);
}

.elevation-01 {
  box-shadow: 0 8px 12px  1px rgba(34,0,51,0.04), 
              0 3px 16px  2px rgba(7,48,114,0.12), 
              0 5px 10px -3px rgba(14,13,26,0.12);
}

.elevation-02 {
  box-shadow: 0 16px 24px 2px rgba(34,0,51,0.04),
              0 6px  32px  4px rgba(7,48,114,0.12), 
              0 8px  12px -5px rgba(14,13,26,0.12);
}

.elevation-03 {
  box-shadow: 0 24px 38px  3px rgba(34,0,51,0.04),
              0 10px 48px  8px rgba(7,48,114,0.12),
              0 12px 16px -6px rgba(14,13,26,0.12);
}`

Which would render:

<img width="1119" alt="Screen Shot 2019-10-15 at 5 34 53 PM" src="https://user-images.githubusercontent.com/1461798/66871662-1f2f1400-ef72-11e9-8ca4-bd2ddd1a8e69.png">

Class names are simply for the example.

Live example in CodePen: https://codepen.io/shorlander/pen/zYYqVyR

**Comment by craigcook** [comment]
Note that some of the color values in https://github.com/mozilla/protocol/issues/456#issuecomment-542415196 don't map to current tokens. I think we're going to use a ink for shadows, or we might iterate on it further but we should at least stick to tokens from the brand palette.

**Comment by shorlander** [comment]
Updated to use the right brand colors.

```
.elevation-00 {
  border: 1px solid hsla(261, 50%, 13%, .24);
}

.elevation-01 {
  box-shadow: 0 8px 12px  1px hsla(261, 50%, 13%, .04),
              0 3px 16px  2px hsla(220, 79%, 17%, .12),
              0 5px 10px -3px hsla(261, 50%, 13%, .12);
}

.elevation-02 {
  box-shadow: 0 16px 24px  2px hsla(261, 50%, 13%, .04),
              0 6px  32px  4px hsla(220, 79%, 17%, .12),
              0 8px  12px -5px hsla(261, 50%, 13%, .12);
}

.elevation-03 {
  box-shadow: 0 24px 38px  3px hsla(261, 50%, 13%, .04),
              0 10px 48px  8px hsla(220, 79%, 17%, .12),
              0 12px 16px -6px hsla(261, 50%, 13%, .12);
}
```

**Comment by craigcook** [comment]
Done in https://github.com/mozilla/protocol-tokens/commit/cc7448e0d5fafa202f02dc9f7b5db4aa1cb49039
