### ISSUE TITLE
Add tokens for border radii (rounded corners)

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#457]
We should standardize a common set of radii (radiuses?), e.g.:

```
$border-radius-sm: 2px;
$border-radius-md: 4px;
$border-radius-lg: 6px;
```

**Comment by stephaniehobson** [comment]
I agree, let's have a single source of truth for this. Have we seen this kind of variety in designs? I think I've only seen 2px so far.

**Comment by Errolyn** [comment]
The shadow boxes use 6px

**Comment by craigcook** [comment]
Firefox buttons have 4px corners.

This isn't dev-ready, it requires a design decision to set standards for corner roundness so we can commit them to tokens.

**Comment by craigcook** [comment]
There are also a bunch of 16px corners on accounts.firefox.com

**Comment by craigcook** [comment]
We've settled on the follow values to start: 2px, 4px, 8px, and 16px.

If at some point we find legit use cases for more in-between values like 6px or 12px etc, we can always expand the set.

**Comment by Errolyn** [comment]
Should we change the emphasis box to one of the standard sized then and should it be 4px or 8px if we decide to go that route? it is using 6px right now.

**Comment by craigcook** [comment]
Yeah we should update the emphasis box once the tokens land (I'll have a PR for that shortly). I think it'll be 8px and 16px will be used very rarely.

We've been hashing out updates to emphasis box over in #499
