### ISSUE TITLE
Notification Bar: Add optional link cta

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/protocol#460]
## Description

Notification bars should support an optional link cta.

![image](https://user-images.githubusercontent.com/30483988/62721344-dd597e80-b9c0-11e9-80da-b6adcee30b4b.png)

[Continuation of work in PR  #431]

**Comment by amychurchwell** [comment]
The css styles are all in place for including a link inside the notification banner. Just needs to be included as an option in the JS:
https://github.com/mozilla/protocol/blob/master/src/assets/js/protocol/protocol-notification-bar.js#L37-L41

**Comment by olsenme** [comment]
I'd be willing to take on this issue if not assigned already

**Comment by amychurchwell** [comment]
Hi @olsenme! Feel free to pick this up.

**Comment by olsenme** [comment]
sure do I need to get assigned?

**Comment by amychurchwell** [comment]
@olsenme not technically as a contributor, but I can go ahead and put your name on it. 🙂

**Comment by olsenme** [comment]
Thanks @amychurchwell  ok to go ahead and fork? The only I reason I asked to be assigned was because I noticed there were alot of other mozilla projects that had multiple comments, and it was hard to tell if someone was working on them or not. Thanks so much.

**Comment by amychurchwell** [comment]
@olsenme yes, feel free to pick this up. 🙂

**Comment by olsenme** [comment]
@amychurchwell  I'm sorry it's taken me a while to get to this. I saw the documentation about pushing to demo and master, but am I just forking and creating my own branch to merge into the repo for this?

**Comment by amychurchwell** [comment]
hi @olsenme! as a contributor, you don't need to worry about pushing to production or creating demos.

To contribute to github repos (like this one) you will have to:
1. create a fork.
2. create a new branch and push desired changes to that branch.
3. open a pull request in this repo from that forked branch.

see: https://guides.github.com/activities/forking/

**Comment by olsenme** [comment]
ok thanks so much @amychurchwell  just wanted to make sure to follow flow. Sorry if that seemed an insignificant question

**Comment by amychurchwell** [comment]
@olsenme no insignificant questions here! ask away! 🙂

**Comment by amychurchwell** [comment]
@olsenme are you still working on this issue?

**Comment by olsenme** [comment]
@amychurchwell  I am so sorry. I've been bogged down with interviews. I should have available time this week to get it done.

**Comment by amychurchwell** [comment]
@olsenme no rush! just checking in.

**Comment by olsenme** [comment]
@amychurchwell  I'm so sorry. I've been down with pneumonia, but wanted to let you know I haven't forgotten and thank you for your patience with me

**Comment by amychurchwell** [comment]
@olsenme I am going to remove your assignment. You are still more than welcome to submit a PR for this.

**Comment by stevejalim** [comment]
I've had a swing at this, because it meets a need I have over on github.com/mdn/developer-portal

**Comment by vibhuti019** [comment]
Is this issue open?

**Comment by craigcook** [comment]
> Is this issue open?

There's already a pull request to address it (https://github.com/mozilla/protocol/pull/534), it's just waiting for review and the team has been busy. Sorry for the delay.
