### ISSUE TITLE
Design/Develop Offer Component

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#462]
The plan component is a new component that allows a comparison for up to 3 different tiers of subscription services/plans to be compared. 

See: 
https://www.huffpost.com/subscribe?ncid=huffpost_globaldesk_ct6htebthyu#offer-module__offers
https://products.office.com/en-us/compare-all-microsoft-office-products?&rtc=1&activetab=tab%3aprimaryr2

Requirements would be: 
Title of Plan
Cost
Features of the plan
A button to initiate an action (like buy

**Comment by stephaniehobson** [comment]
I see the two boxes that combine into one as a component. That component can then have anything in it. In this case it has a headline, download button atom, and a new "feature list" (or something like that) atom which is the centered list content.

**Comment by wboucherfischer** [comment]
Draft of competitive analysis @johngruen @dzingeek 
https://docs.google.com/presentation/d/1wXJMmM6EVVNFChkKYfcsS3mCjgaqB7uOb9jOypX5fN8/edit?usp=sharing

I'm working on designs now.
