### ISSUE TITLE
Fx Text link CTAs should use the Metropolis Font

### ISSUE THREAD

**Issue by dzingeek** [mozilla/protocol#468]
All Firefox text link CTAs should use the Metroplis font. 

**See screenshot for reference**
![Screen Shot 2019-08-20 at 1 17 49 PM](https://user-images.githubusercontent.com/3740746/63381187-0842bb80-c34d-11e9-83e3-b96e56f162d2.png)

**Comment by stephaniehobson** [comment]
@dzingeek And buttons too, right?

**Comment by dzingeek** [comment]
yes and buttons too. we will add another github issue for buttons we just haven't done it yet. but that issue will have more than just the font outlined.
