### ISSUE TITLE
New Component: Sub Navigation

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#471]
The new `/firefox/enterprise/` component being built in https://github.com/mozilla/bedrock/issues/7491 features a sub navigation component.

![image](https://user-images.githubusercontent.com/400117/63582160-74f9c800-c590-11e9-89a6-9df7ea5e1f00.png)

So far it is a unique snowflake and is pretty much a simple horizontal list that sits under the main navigation component. The component is static (non-sticky) and links to in-page anchors. It stacks links in a simple vertical list on small viewports.

Bedrock also has other variations of sub navigation menus on other (non-protocol) pages:

![image](https://user-images.githubusercontent.com/400117/63582274-b0949200-c590-11e9-969c-ae19e78e18a8.png)

These are slightly more complex, as they are sticky on scroll, feature a secondary download CTA, and are not visible on small viewports. They also link to other pages/sites, vs in-page anchors.

We should clearly define what our needs are for sub navigation, and design a single component that can be used uniformally across pages.

**Comment by alexgibson** [comment]
Since the menu titles turned bold in https://github.com/mozilla/protocol/issues/481, the sub navigation links on the /enterprise page feel inconsistent:

![image](https://user-images.githubusercontent.com/400117/65042740-66b18880-d951-11e9-8ae7-0d6a6e080ac1.png)

We should probably turn the sub navigation links bold to match, but then the word "Enterprise" is already bold. We may need to rethink some of the styles.

**Comment by stephaniehobson** [comment]
Bold menu and not-bold submenu is consistent with what I'm seeing on the Privacy wireframes so I don't think we need to rush a fix for this.

It would be nice to have this component flushed out though.

**Comment by alexgibson** [comment]
Here's how the sub-nav looks for the new privacy pages. At this time, I may at least update the sub-nav on /enterprise to conform with what's here:

<img width="655" alt="Screenshot 2019-09-24 at 17 49 51" src="https://user-images.githubusercontent.com/400117/65532528-de545a00-def3-11e9-888e-f8c590e045d3.png">

**Comment by alexgibson** [comment]
With the privacy pages being launched soon, this new sub component will now exist on three separate pages. Three times is a patern, as they say. 

I think this should now be made into a component.

**Comment by dzingeek** [comment]
This is now being handled by the new nav system linked in [this github issue](https://github.com/mozilla/protocol/issues/544)

**Comment by alexgibson** [comment]
Superseded by https://github.com/mozilla/bedrock/pull/9650
