### ISSUE TITLE
Specify Lifecycle Components in Protocol

### ISSUE THREAD

**Issue by ejregithub** [mozilla/protocol#475]
## Description

We're building the first Lifecycle page and need a designer to specify the components in Protocol

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by hoosteeno** [comment]
I'm pulling this from the present sprint until it's clearer how Protocol workflow/priorities will work.

**Comment by hoosteeno** [comment]
Closing in favor of a better-articulated future card.
