### ISSUE TITLE
Specify Lockwise Components in Protocol

### ISSUE THREAD

**Issue by ejregithub** [mozilla/protocol#476]
## Description

We're building the Lockwise product page and need a designer to specify the components in Protocol

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by hoosteeno** [comment]
Pulling this out of the present sprint until it's clearer how Protocol priorities and workflow will work.

**Comment by hoosteeno** [comment]
Closing in favor of a better-articulated future card.
