### ISSUE TITLE
Update details component to respond to esc key

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#478]
If details are expanded and focus is inside the details (or on the summary) the escape key should collapse the details and put focus on the summary.

**Comment by stephaniehobson** [comment]
Closing in favour of https://github.com/mozilla/protocol/issues/551

**Comment by janbrasna** [comment]
FWIW even the og ‹details› ‹summary› element in plain vanilla html page without any styling and behav only responds to spacebar and enter to open and close. And that both the Protocol-styled Details element and the custom Details component already do wonderfully.
