### ISSUE TITLE
Download buttons should be inline-block instead of block level?

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#486]
## Description

Download button containers are block level, meaning they take up 100% of their parent's container width. They should probably be inline-block?

### Steps to reproduce

1. Visit https://protocol.mozilla.org/patterns/molecules/download-button.html

### Expected result

![image](https://user-images.githubusercontent.com/400117/64979236-36191280-d8af-11e9-83e6-84af9a60968e.png)

### Actual result

![image](https://user-images.githubusercontent.com/400117/64979257-44672e80-d8af-11e9-9547-51183f2c742c.png)

### Environment

Any browser.

**Comment by RyanWils** [comment]
Hi I am fairly new to the open source community and this looks like a good bug to start with. 
If it is okay with you, I would like to work on this bug.

**Comment by thisisabhinay** [comment]
@RyanWils What's the status update? If you are not working on it then I would like to continue working on this one.

**Comment by RyanWils** [comment]
Feel free to work on it, I am having issues with the launching of the local instance. 
I have opened a ticket about my issue, but they have not got back to me yet. 
Issue - #501

**Comment by tikhsuP** [comment]
@alexgibson @amychurchwell, my above PR generates this result : 
![Screenshot (262)](https://user-images.githubusercontent.com/42881874/70368996-83b68180-18d8-11ea-91a1-cd75d9a887fa.png)

Do I need to change the [Download Button (Secondary)](https://protocol.mozilla.org/patterns/molecules/download-button.html#download-button-secondary)  to this 
![Screenshot (263)](https://user-images.githubusercontent.com/42881874/70369034-1c4d0180-18d9-11ea-87d8-add50d27ba89.png) as well?
