### ISSUE TITLE
Rename `mzp-c-box-emphasis` to `mzp-c-emphasis-box`

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/protocol#489]
### Description

It is a little confusing that the [emphasis box component](https://protocol.mozilla.org/patterns/molecules/emphasis-box.html) uses the class name `mzp-c-box-emphasis`, we should change this to `mzp-c-emphasis-box` for consistency.

**Comment by rajneeshkumar146** [comment]
Hi @amychurchwell,  I want to claim it

**Comment by amychurchwell** [comment]
@thisisabhinay as a courtesy, we should check in with the contributor who was originally interested. If they are not, you are welcome to pick this up.

@rajneeshkumar146 - are you still interested in working on this issue?

**Comment by Patil2099** [comment]
@amychurchwell Can I work on this issue?

**Comment by amychurchwell** [comment]
Hi all, I am going to close this bug because I no longer think this is worth creating a breaking change over. 🙂 thank you all for your interest in helping us with this issue.

**Comment by stephaniehobson** [comment]
Oh oops, I merged the open PR 😅

**Comment by amychurchwell** [comment]
@stephaniehobson no worries! should we make an issue to rename in bedrock?

**Comment by stephaniehobson** [comment]
Naw, I think it'll be covered by the "Upgrade to Protocol 10" issue whenever that gets filed.
