### ISSUE TITLE
Component Change Request - Emphasis Box

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#499]
### Please describe the use case(s) for this component 

To call out or emphasize a primary CTA. Can be used to break up a page to highlight important content, for example "Download Firefox" or "Sign Up for a Firefox Account". It can house an FxA signup form.

An emphasis box is not a card. It's not clickable, it's a container for other content. Use sparingly to emphasize important content. If everything is emphasized, nothing is emphasized.

Should never have an emphasis box within an emphasis box.

### Please describe the change you wish to see

- Should use token values for border-radius and box-shadow (tokens TBD).
- We'll revisit padding. It should have default basic padding, with an easy override.
- Shadow variations - flat, elevated
- We'll choose a fixed border radius (and use the token) with usage guidelines around nesting elements.
- Dark theme variant.

### Please describe why these changes need to be made

- This is an iteration to add clarity and consistency around the use of emphasis boxes.
- To give designers an opportunity to highlight content.

### Please provide any designs or prototypes of the proposed changes

To come

### Please describe where this component is currently in use

https://www.mozilla.org/en-US/firefox/69.0/whatsnew/
https://www.mozilla.org/en-US/firefox/firstrun/
https://www.mozilla.org/en-US/firefox/accounts/ (signed out)

### Please describe what this component should do in the following conditions

* When set in front of a dark background - should have a non-white background color, either slightly off-white or something else that contrasts appropriately with the dark background.
* When set in front of a light background - white background.
* When viewed in a mobile/responsive viewport - maybe adjust padding for small screens.

### Is the development of this component a blocking dependency for other work? Please explain if so

Nope.

**Comment by justinkropp** [comment]
This is another external example of the behavior of an emphasis box.

<img width="1471" alt="Screen Shot 2019-09-30 at 9 25 05 PM" src="https://user-images.githubusercontent.com/1461798/65927823-465de100-e3c9-11e9-968f-114f91476068.png">

**Comment by craigcook** [comment]
> This is another external example of an emphasis box, from [Sketch](https://www.sketch.com/).

That's very similar to our "Compact Callout," which doesn't currently reside in a box, it's a full-width section: https://protocol.mozilla.org/demos/call-out-compact.html

**Comment by craigcook** [comment]
https://www.mozilla.org/firefox/installer-help/

![image](https://user-images.githubusercontent.com/205591/66065896-3fd08600-e4fd-11e9-9b50-134494a5eb2d.png)

This is an emphasis box used for a secondary CTA that just needs a bit more oomph so it isn't overlooked (this is also a super bare-bones page; there could be other ways to apply oomph but throwing it in an emphasis box was easy).

**Comment by stephaniehobson** [comment]
There's also one on the [new /firefox homepage](https://www-demo4.allizom.org/en-US/firefox/):

<img width="1213" alt="Screen Shot 2019-10-03 at 10 52 55" src="https://user-images.githubusercontent.com/854701/66151360-00249f80-e5cc-11e9-9ab6-3f8b9a88e56d.png">

This might be an example of a dark theme?
