### ISSUE TITLE
Content Layout: Adding a third size (S, MD, LG)

### ISSUE THREAD

**Issue by dzingeek** [mozilla/protocol#505]
Right now we only have two sizes for content layout 736px wide and 1312px wide. This issue is there are times when we need a size in-between to make text areas more legible.

This text is too long which makes it harder to read/scan
![Screen Shot 2019-10-09 at 9 43 46 AM](https://user-images.githubusercontent.com/3740746/66502042-63557c80-ea79-11e9-9077-cbe471367d1e.png)

I am proposing we have 3 sizes S/M/L

- **S = 736** (this is for times we have a wall of copy "privacy notices")
- **MD = 992** (for those times illustrated in the image attached)
- **LG = 1248** (navigation, hero images and other areas where the text is large or minimal)

**Comment by thisisabhinay** [comment]
@dzingeek I would like to work on it

**Comment by stephaniehobson** [comment]
@thisisabhinay and @craigcook I've been talking about this issue with @dzingeek and I think it would be best if I took it over since I have a clear idea of what she wants and I can use some work I've already done as a reference.

**Comment by dzingeek** [comment]
@stephaniehobson I made two small tweaks on the sizes based on the fact that I put the wrong ones in there the first time ;)

**Comment by stephaniehobson** [comment]
A recent conversation with @dzingeek revealed that these might be changing. I'm going to take the dev ready tag off this until the grid stuff has been decided.

**Comment by craigcook** [comment]
See https://github.com/mozilla/protocol-tokens/issues/73 for work on updating token values. I think in Protocol we would then map these to some theme classes for containers, something like:

```
.mzp-l-content {
   &.mzp-t-content-sm {
        max-width: $content-sm;
    }
    &.mzp-t-content-md {
        max-width: $content-md;
    }
    &.mzp-t-content-lg {
        max-width: $content-lg;
    }
}
```

**Comment by craigcook** [comment]
Comparison of old sizes to proposed new sizes: https://demo2--mozilla-protocol.netlify.com/demos/content-width.html
Demo page with a mix of different sized containers: https://demo2--mozilla-protocol.netlify.com/demos/content-width-prototype.html

**Comment by mheubusch** [comment]
@dzingeek can you review craigcook's proposal and if approved, add the label ready for dev?

**Comment by dzingeek** [comment]
@craigcook those look good to me, nice work!

**Comment by stephaniehobson** [comment]
New tokens are in https://github.com/mozilla/protocol-tokens/pull/81
