### ISSUE TITLE
Create a Form component [forms]

### ISSUE THREAD

**Issue by dzingeek** [mozilla/protocol#508]
We need flexible but consistent forms on our website properties.

These specs are based off of the input fields issue https://github.com/mozilla/protocol/issues/430

Attached are specs + examples of different form types build from all the same atoms
![form-specs](https://user-images.githubusercontent.com/3740746/67120575-6dc0f600-f19e-11e9-848c-fa2c7e5a9462.png)

![form-examples](https://user-images.githubusercontent.com/3740746/67120577-6e598c80-f19e-11e9-9bd1-c6502621f6b8.png)

**Comment by dzingeek** [comment]
link to box shadow issue https://github.com/mozilla/protocol/issues/456#issue-478055351

**Comment by stephaniehobson** [comment]
I was working on these styles and tried to test the form I was working on as if it was a newsletter form... and it's not. And I was reminded of: https://github.com/mozilla/protocol/issues/334

It might be a good time to add an icon or something to the spec. To try to give a visual distinction between newsletter and FxA sign-up.

**Comment by stephaniehobson** [comment]
I've gotten started on this. I could use some direction on error message styling:

<img width="487" alt="Screen Shot 2019-10-28 at 09 25 14" src="https://user-images.githubusercontent.com/854701/67696919-ebd28900-f964-11e9-8e26-5a3f7b30641e.png">

**Comment by dzingeek** [comment]
@stephaniehobson thanks for flagging this I totally forgot about this type of error message. See attached specs, let me know if you have any other questions or run into an issues.

![Screen Shot 2019-10-29 at 10 00 02 AM](https://user-images.githubusercontent.com/3740746/67790813-9f09b380-fa33-11e9-8fa7-67552a7c5d1b.png)

**Comment by dzingeek** [comment]
Since this component is built from a series of atoms here are all github issues for those atoms. Specs for some of those atoms are still being worked on and will be updated shortly.

[input field](https://github.com/mozilla/protocol/issues/430)
[radio button + check box](https://github.com/mozilla/protocol/issues/439)
[button](https://github.com/mozilla/protocol/issues/429)
[dropdown](https://github.com/mozilla/protocol/issues/435)
