### ISSUE TITLE
Update defaults for mzp-t-dark

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#515]
In our links file we make links in `mzp-t-dark` components white. But we don't change the default text colour or the background colour anywhere. 

This means that the theme class cannot be used to alter the theme of components by itself and can only be used with components which support it.

In bedrock when we use the dark theme we have to declare styles like:
```
.mzp-t-dark {
    background-color: $color-off-black;
    color: $color-white;
}
```

And in our IE fallback sheet we have:
```
// make sure dark components have correct background and text color
.mzp-t-dark {
    background: $color-off-black;
    color: #fff;

    h1, h2, h3, h4, h5, h6 {
        color: #fff;
    }
}
```

This theme should produce readable text when it is applied. Styles can then be tweaked from there.

I suggest:
```
.mzp-t-dark {
    background-color: #000000;
    color: $color-white;

    .mzp-t-firefox & {
          background-color: $color-off-black;
    }
}
```

I think this will be a breaking change and I will do some testing in bedrock to see if this is possible at all.

**Comment by stephaniehobson** [comment]
A survey of bedrock suggests this will break more than a few pages:

- firefox/privacy/products
- welcome
- developer/firstrun
- firefox/concerts
- firefox

It feels like the right thing to do to set a background colour when the foreground colour is changed. Is it worth the pain?

**Comment by stephaniehobson** [comment]
Another option would be to not define the link colour in the links file and require it to be declared specifically on supporting components.

That will break things in different ways. Ways that would be much faster/simpler to fix than applying a background colour by default.

**Comment by stephaniehobson** [comment]
A Slack channel conversation on this turned up a vote for removing the default link change.

**Comment by craigcook** [comment]
https://github.com/mozilla/protocol/issues/853
