### ISSUE TITLE
Fix typo in 'Emphasis Box' docs

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/protocol#523]
## Description

`mzp-c-box-emphasis` should be changed to `mzp-c-emphasis-box` on https://protocol.mozilla.org/patterns/molecules/emphasis-box.html

**Comment by tikhsuP** [comment]
So, is the typo needed to be fixed in  protocol/src/patterns/molecules/emphasis-box/medium-emphasis-box.hbs ?

**Comment by tikhsuP** [comment]
Can you please guide me that this typo needs to be fixed in which document?
I have checked protocol/src/patterns/molecules/emphasis-box/medium-emphasis-box.hbs files under issues #489 and #502.

**Comment by tikhsuP** [comment]
@amychurchwell, I am interested to work on this issue but I haven't been able to find the appropriate file to be corrected. However, I have investigated the creation of ### **Emphasis Box** page(#385) and the changes made to files  CHANGELOG.md [https://github.com/mozilla/protocol/blob/66955b8faa7c7811fd0636e141ebfe3c30d16300/CHANGELOG.md](url), _emphasis-box.scss [https://github.com/mozilla/protocol/blob/66955b8faa7c7811fd0636e141ebfe3c30d16300/src/assets/sass/protocol/components/_emphasis-box.scss](url) and medium-emphasis-box.hbs[https://github.com/mozilla/protocol/tree/66955b8faa7c7811fd0636e141ebfe3c30d16300/src/patterns/molecules/emphasis-box](url) under #489(#502) and #498. 
Can you please guide me to the file to be corrected ?

**Comment by tikhsuP** [comment]
@amychurchwell, I am interested to work on this issue but I haven't been able to find the appropriate file to be corrected. However, I have investigated the creation of ### Emphasis Box page(#385) and the changes made to files mozilla/protocol/CHANGELOG.md,  protocol/src/assets/sass/protocol/components/_emphasis-box.scss  and  protocol/src/patterns/molecules/emphasis-box/medium-emphasis-box.hbs under #489(#502) and #498.
Can you please guide me to the appropriate file?

**Comment by amychurchwell** [comment]
@tikhsuP Apologies! This issue is a dupe of #489, there is no change to be made. Thank you for your interest.

**Comment by tikhsuP** [comment]
👍 No worries @amychurchwell 
Thanks.
