### ISSUE TITLE
[bug] Notification bar line height breaking container.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/protocol#525]
## Description

The [line-height](https://github.com/mozilla/protocol/blob/master/src/assets/sass/protocol/components/_notification-bar.scss#L30-L31) is knocking longer text out of it's container at certain screen sizes.

<img width="495" alt="Screen Shot 2019-11-26 at 3 23 52 PM" src="https://user-images.githubusercontent.com/30483988/69680793-d6827480-1060-11ea-9aea-6903e0ecf578.png">
<img width="392" alt="Screen Shot 2019-11-26 at 3 23 44 PM" src="https://user-images.githubusercontent.com/30483988/69680794-d6827480-1060-11ea-9ef8-2b6390365e67.png">

**Comment by tikhsuP** [comment]
I am willing to work on this issue, please assign it to me.

**Comment by amychurchwell** [comment]
@tikhsuP assigned! Thank you for your interest!

**Comment by tikhsuP** [comment]
Thanks @amychurchwell 
May I know the expected line height ?

**Comment by amychurchwell** [comment]
@tikhsuP perhaps it is a case of only declaring line height at certain screen width? (media queries listed on the [Protocol tokens page](https://protocol.mozilla.org/fundamentals/tokens.html)) 
However, if you think 12px looks fine we can take a look in code review.

**Comment by tikhsuP** [comment]
Thanks @amychurchwell , I understand that. 
I have made a pull request, do tell me if any changes are needed. I am willing to learn and improve as much I can.

**Comment by tikhsuP** [comment]
@amychurchwell
I reviewed my PR #528 and it actually isn't a solution to this bug, apologies!
So, I have made another PR #530 and it works fine on my side.
Please review.

**Comment by tikhsuP** [comment]
@amychurchwell what is the status of this issue?
Is my PR of any help?

**Comment by amychurchwell** [comment]
@tikhsuP Thank you for the pull request! We have been quite busy, but I will review it when I'm able. 👍

**Comment by tikhsuP** [comment]
I understand @amychurchwell .
No worries.

**Comment by alexgibson** [comment]
This bug is effecting: https://github.com/mozilla/bedrock/issues/7615

![image](https://user-images.githubusercontent.com/400117/74819144-dc05f880-52f7-11ea-9eaf-6f272ffef3aa.png)
