### ISSUE TITLE
Level-4 Heading Font Size too Large

### ISSUE THREAD

**Issue by wthayer** [mozilla/protocol#532]
## Description

On the [Root Store Policy](https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/) page, the level-4 (e.g. 3.1.2.2) headings are much larger than the level 1-3 headings, making the page difficult to read.

### Steps to reproduce
Navigate to https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/ in Firefox

### Expected result
4th level headings smaller than higher level headings

What should happen?

### Actual result

What happened.

### Environment

What browser and operating system are you using?
Firefox 71 Release; Firefox 73 Nightly on macOS

**Comment by craigcook** [comment]
We're revising the type scale so this will finally be addressed.
