### ISSUE TITLE
Vertical Rhythm 

### ISSUE THREAD

**Issue by mheubusch** [mozilla/protocol#536]
Please use this template to request a new component.
If you're not sure whether a component already exists,
go ahead and file the issue here, and the team will triage appropriately.

Fill in as many sections as possible below.

### Please describe the use case(s) for this component

What does the component do? In what contexts is it used. Be as specific as possible.

### Please provide any designs or previous implementations of the proposed component

Add screenshots, mockups, code prototypes, etc. in this section.

## Please describe what this component does in the following conditions

* When set in front of a dark background
* When set in front of a light background
* When viewed in a mobile/responsive viewport

### Please provide examples of this type of component in use in non-Mozilla web properties

Add screenshots and links to web properties that use a similar component.
(We ask for this because we want to make sure we are following industry conventions while building components)

### Is the development of this component a blocking dependency for other work? Please explain if so

Generally speaking component definition should happen after a singleton instance has been developed,
or if the Protocol team has come to a consensus on need.

**Comment by mheubusch** [comment]
@shorlander can you update the description?

**Comment by justinkropp** [comment]
After some discussion, @shorlander, @dzingeek, and I arrived at a first-stab at vertical rhythm guidelines. They are as follows (with examples):

Vertical spacing between content sections on a site have two values:

- `96px`
- `192px`

`192px` spacing is used to separate **unrelated** sections on a page by inserting more _white space_ between those sections. An examples would be separating a section of features from a newsletter call-out box just below that list of features.

`96px` spacing is used to separate **related** sections of content that live together as a group (ex. would be the above list of features). 

@shorlander — any additional thoughts?

- With annotated vertical spacers: ![Screen XL](https://user-images.githubusercontent.com/1461798/79004128-19317e80-7b22-11ea-93e7-dac028af326f.jpg)
- Without annotations: ![Screen XL Copy](https://user-images.githubusercontent.com/1461798/79004137-1d5d9c00-7b22-11ea-97a5-bd97aa877f09.jpg)

**Comment by dzingeek** [comment]
We might want to think about a third size but for now I think this a great starting point/foundation. nice work @justinkropp

**Comment by stephaniehobson** [comment]
@justinkropp Are the values the same for mobile?

**Comment by justinkropp** [comment]
@stephaniehobson Good question. They're not the same on mobile. I'll post specs and some visuals for those specs here today.

**Comment by justinkropp** [comment]
@stephaniehobson, for small viewports I'd like to use the following vertical spacing rules -- which are similar to those above:

`96px` spacing is used to separate unrelated sections on a page.

`48px` spacing is used to separate related sections of content that live together as a group.

![Screen SM](https://user-images.githubusercontent.com/1461798/79237072-bc90d500-7e3b-11ea-9f96-1ec913a15499.jpg)

**Comment by dzingeek** [comment]
@justinkropp I think we should change the spacing for mobile (separate related sections) to the following. 

**64px** spacing is used to separate related sections of content that live together as a group.

**Comment by justinkropp** [comment]
@dzingeek Agreed. `64px` feels better.

**Comment by dzingeek** [comment]
One more note @justinkropp I think we need another size based. let's chat about this in our working session on friday.

**Comment by dzingeek** [comment]
@stephaniehobson we (@justinkropp + @shorlander and I) decided we need another size for desktop = 96px. 

**So the final spacing sizes for desktop is:
192px – 96px – 64px**

_Note: We might need another size for mobile. Looking into that today/this week._

**Comment by dzingeek** [comment]
@stephaniehobson talked with @justinkropp about mobile vertical spacing and we both agree that we need a third one = 64px

So the final spacing sizes for mobile is:
96px – 64px – 48xpx
