### ISSUE TITLE
Update navigation menu hover state

### ISSUE THREAD

**Issue by mheubusch** [mozilla/protocol#540]
Update the navigation menu entry and prototype to reflect the new styling and hover state. https://protocol.mozilla.org/patterns/molecules/menu.html

What's changing?
Grey box over selectable item, instead of text underline. 

And why
To reflect preferred styles

Add screenshots, mockups, code prototypes, etc. in this section.

In order to assess the risk of changes, we need to know where components exist in the wild.
In main navigation menu of mozilla.org

### Please describe what this component should do in the following conditions

* When set in front of a dark background
* When set in front of a light background
* When viewed in a mobile/responsive viewport

This work is required to demonstrate proposed design and obtain sign off.

**Comment by dzingeek** [comment]
@craigcook  any ETA on when you might have a demo or two for us to review?

**Comment by craigcook** [comment]
> @craigcook any ETA on when you might have a demo or two for us to review?

https://codepen.io/craigcook/pen/LYVxgyd?editors=1100

This is what I've got so far, still rough but gives us a starting point to discuss for further refinement.

**Comment by dzingeek** [comment]
I think this should be tied to the [epic "Fx Modular Navigation System" issue](https://github.com/mozilla/protocol/issues/544)

**Comment by alexgibson** [comment]
Closing this as superseded by https://github.com/mozilla/bedrock/pull/9650
