### ISSUE TITLE
Firefox Modular Navigation System (global)

### ISSUE THREAD

**Issue by dzingeek** [mozilla/protocol#544]
This is the beginning of creating a modular navigation system for all Firefox web properties. 

**It should include:**
- main navigation with modular components (buttons, icons, links/labels, logos...)
- sub nav (when applicable) with modular components (labels/links, buttons, logos...)
- dropdown (when applicable) with modular components (labels/links, buttons, logos...)
- footer with modular components (logos, labels/links, icons...) and Mozilla sub-section

**Resources**
1. [sketch file with specs](https://share.goabstract.com/6fbedca6-68fb-4d79-8482-e9def9de40fc?sha=f683d601a256f4e95e1c91cd2db1809e863f81ac)
2. [Main Nav PNG](https://user-images.githubusercontent.com/3740746/75300096-b8f1b200-57eb-11ea-978f-c18fd4e17afd.png)
3. [Dropdowns PNG](https://user-images.githubusercontent.com/3740746/75300102-bc853900-57eb-11ea-9c1d-c1635c698b5a.png)
4. [Footer PNG](https://user-images.githubusercontent.com/3740746/75300104-be4efc80-57eb-11ea-86b7-a82b39f5c60b.png)

______________
_Note: This is currently only for Firefox but this system will also be adapted for Mozilla web properties at a later date (with moz look and feel)_

**Comment by dzingeek** [comment]
Linking this github issue here to make sure these things are reviewed and addresses if needed as we build out the new nav system:

https://github.com/mozilla/bedrock/issues/8937

**Comment by alexgibson** [comment]
Closing this as superceded by https://github.com/mozilla/bedrock/issues/9220
