### ISSUE TITLE
Confirm that our font mixins are still working for us from a design perspective

### ISSUE THREAD

**Issue by Errolyn** [mozilla/protocol#547]
We have had a couple of requests recently to using font sizing outside of our font mixins using manual break points. We should confirm with design that the break points we have are still working for us and that we don't need to add/remove/change something. The latest page is the 404/500 pages needing some special font treatment.

**Comment by alexgibson** [comment]
Possibly related issues:

- https://github.com/mozilla/protocol/issues/410
- https://github.com/mozilla/protocol/issues/417

**Comment by stephaniehobson** [comment]
Addressing this on the meat layer.
