### ISSUE TITLE
Notification bar should use box-sizing: border-box;

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#549]
## Description

Because the notification bar component has [default padding](https://github.com/mozilla/protocol/blob/master/src/assets/sass/protocol/components/_notification-bar.scss#L19) values, the notification container can break out of the viewport at sizes that specify a [min-width](https://github.com/mozilla/protocol/blob/master/src/assets/sass/protocol/components/_notification-bar.scss#L22).

The component should use `@include border-box;` to take into account the extra padding.

### Steps to reproduce

This is much clearer on bedrock where we have the notification is use, but you can see the issue on this URL: https://protocol.mozilla.org/patterns/molecules/notification-bar.html

Resize the browser and notice the notification breaks out of its container at around 520px.

### Expected result

The notification should adapt well to any screen size.

### Actual result

The notification can be wider than it's container.

### Environment

Firefox Nightly

**Comment by alexgibson** [comment]
Screenshot of bug when running bedrock locally:

![image](https://user-images.githubusercontent.com/400117/75696793-0b2b4b00-5ca4-11ea-984d-19a2dd64e8de.png)

**Comment by stephaniehobson** [comment]
I think it would be a good idea to also remove the min-width declaration. It doesn't seem to be needed since the notifications always fill the available width (until they reach their max).
