### ISSUE TITLE
Modify/create another hero component to feature a center image in the Welcome page template

### ISSUE THREAD

**Issue by ejregithub** [mozilla/protocol#556]
## Description

Request is to modify/create another hero component used in the Welcome page template to feature a center image

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The component is available for use
- [ ] For the Sync browser welcome page, the component is used and the Sync image (TBD) is applied

**Comment by tikhsuP** [comment]
@ejregithub 
@alexgibson 
I am interested in knowing more about this issue.

**Comment by stephaniehobson** [comment]
Can be achieved with currently available components.
