### ISSUE TITLE
Modal close button is too small

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#557]
![Screen Shot 2020-03-25 at 17 17 34](https://user-images.githubusercontent.com/854701/77597575-8acfc280-6ebc-11ea-9b42-79b8a736d1a5.png)

**Comment by tikhsuP** [comment]
@stephaniehobson 
I worked on this issue and I found out that right now the background image is 16px in height and 16px in width.

 `.mzp-c-modal-button-close {
        @include background-size(16px 16px);`
} 

in the file [src/assets/sass/protocol/components/_modal.scss](https://github.com/mozilla/protocol/blob/master/src/assets/sass/protocol/components/_modal.scss)

The issue can be resolved by increasing the size to:
Height: 30px
Width: 30px

## Result

![Screenshot from 2020-03-26 09-07-11](https://user-images.githubusercontent.com/42881874/77607720-3fabc300-6f41-11ea-9e0c-1f3f8090810a.png)

**Comment by tikhsuP** [comment]
@stephaniehobson Please review.

**Comment by craigcook** [comment]
I rebased, updated the changelog, and merged this manually in https://github.com/mozilla/protocol/commit/ce77ad5b6a03d336330d45b3d1c8253323ad1bf3

Thanks for the pull request!
