### ISSUE TITLE
Spacing in the Notification Bar

### ISSUE THREAD

**Issue by tikhsuP** [mozilla/protocol#559]
## Description

There should be a WHITE SPACE between the text in PARAGRAPH tag and ANCHOR tag (CTA link) in the notification bar.

### Steps to reproduce

In the [Notification Bar](https://protocol.mozilla.org/patterns/molecules/notification-bar.html), we are given the demonstration of the notification bars. 

Click on the OPEN NOTIFICATION button:

![Screenshot (28)](https://user-images.githubusercontent.com/42881874/77722363-971a6380-7013-11ea-86a7-aacc1bd20d86.png)

The following popup appears:

![Screenshot (27)](https://user-images.githubusercontent.com/42881874/77722419-b9ac7c80-7013-11ea-943d-2ef08206a0c9.png)
It can be clearly seen that it lacks a white space between the text and CTA link.

This issue does not arise in the Notification Bars given in the `protosite-notification-bar-preview` section, it only arises in the popup notification bar.

### Expected result

The popup notification bar should be similar to the one shown in the preview and should have a white space that separates the text and the CTA link. 
![Screenshot (29)](https://user-images.githubusercontent.com/42881874/77722537-02643580-7014-11ea-9cef-1c3e5dedf09b.png)

**Comment by Aakash2408** [comment]
Can I Take this?

**Comment by tikhsuP** [comment]
Yes @Aakash2408, feel free to work on it.

**Comment by Aakash2408** [comment]
Ok, I will have a look upon code and make the changes. Meanwhile, can you kindly  assign me another issue #582  I have made those changes in local and made a pull request also #583

**Comment by Aakash2408** [comment]
When I click on the open navigation I got this:
![spacing](https://user-images.githubusercontent.com/47134609/81612765-fc2aec80-93fa-11ea-9ae6-4b7d95cd566b.png)

Can you tell about which spacing you are talking?

**Comment by tikhsuP** [comment]
Apologies.
This issue has been fixed.
Feel free to work on another issue : )

Thanks for your interest. @Aakash2408
