### ISSUE TITLE
Content Formatting

### ISSUE THREAD

**Issue by thejeffreytaylor** [mozilla/protocol#56]
Including, but not limited to: 

- Standard notation for dates, places, links, buttons, etc
- Character count guidance
- Content length guidance
- General formatting guidelines for content creators to assist work product is useful and usable for implementation

**Comment by michaelmccombie** [comment]
We should look into 'ch' units for controlling character counts 
https://css-tricks.com/the-lengths-of-css/#article-header-id-11
