### ISSUE TITLE
Implement sticky navigation feature

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#560]
### Please describe the use case(s) for this component

We have a request to make the navigation organism support an optional feature for sticky scrolling. This change comes out of a CRO experiment that is captured in the epic here: https://github.com/mozilla/bedrock/issues/8676

### Please describe the change you wish to see

Add an option to make the navigation component sticky, so that it remains visible on scroll.

### Please describe why these changes need to be made

The CRO experiment showed a significant increase in conversions as a result of sticky navigation, so there is a request to roll this out site wide on www.mozilla.org.

### Please provide any designs or prototypes of the proposed changes

Design discussions and prototypes happened here: https://github.com/mozilla/bedrock/issues/8674

### Please describe where this component is currently in use

It's the primary navigation on nearly every page of www.mozilla.org. The sticky behavior will be optional and disabled by default, so the risk to other sites should be minimal unless they opt-in to the new feature.

### Please describe what this component should do in the following conditions

* When set in front of a dark background

N/A

* When set in front of a light background

N/A

* When viewed in a mobile/responsive viewport

Sticky behavior will happen for desktop sized viewports only, and also requires a minimum viewport height.

### Is the development of this component a blocking dependency for other work? Please explain if so

Yes - we need to implement this in Protocol before bedrock can make use of it downstream.

**Comment by alexgibson** [comment]
@justinkropp WIP demo of the sticky navigation. I'd very much like to get your design / UX feedback at this stage before I finalize things further: https://demo2--mozilla-protocol.netlify.com/demos/navigation.html

Let me know if you would like to meet in person to discuss anything. Thanks!

**Comment by justinkropp** [comment]
@alexgibson I think this feels great from an interaction standpoint(timing, animation speed, etc.). Rather than using a border-bottom, could we use a drop-shadow instead? Something like the following:

`box-shadow: 0 0px 5px 1px rgba(9,32,77,0.12);`

Screenshot below for reference:

<img width="1266" alt="Screen Shot 2020-04-02 at 11 47 11 AM" src="https://user-images.githubusercontent.com/1461798/78269786-08f12200-74d8-11ea-975f-2aa6065a2b94.png">

**Comment by alexgibson** [comment]
Pull request is now ready for code review: https://github.com/mozilla/protocol/pull/561
