### ISSUE TITLE
Update Icons in modules on previous What's New & Moments pages

### ISSUE THREAD

**Issue by ejregithub** [mozilla/protocol#575]
Brand has new icons that need to be added to Protocol.

Those can be referenced here:  https://github.com/mozilla/bedrock/issues/8768

Once added to Protocol, the updates will need to be made in bedrock, which will be managed in this card: https://github.com/mozilla/bedrock/issues/8800

**Comment by stephaniehobson** [comment]
Icons are in Protocol now.
