### ISSUE TITLE
When opening sticky nav at bottom of the screen, some options cut off

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#577]
This is very much an edge case. With a small monitor and a large drop down menu it is possible to have drop down menu options cut off by the bottom of the screen if the menu is opened while the user is at the bottom of the page. Attempting to scroll these options into view then collapse as the menu.

**Comment by Aakash2408** [comment]
Can you please share the images of the screen. I would like to work on this.

**Comment by stephaniehobson** [comment]
Sorry, I don't have time to provide guidance. We will mark bugs that have info and are good for community contribution with the tag "good first bug".

**Comment by stephaniehobson** [comment]
Not able to reproduce.
