### ISSUE TITLE
Newsletter form: add optional subtitle

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#578]
### Please describe the use case(s) for this component

Some instances of the newsletter form have need for a true secondary title in addition to a main title and description. I think we should offer both a subtitle and a description. They should both be optional so you could have one or the other or neither (title should be required).

### Please describe the change you wish to see

- Add a new `h4` between the title and tagline named `mzp-c-newsletter-subtitle`.

### Please describe why these changes need to be made

A new optional subtitle offers more flexibility for different content.

### Please provide any designs or prototypes of the proposed changes

Example form with title, subtitle, and tagline/description:
![image](https://user-images.githubusercontent.com/205591/81106754-fb5dfc00-8eca-11ea-98ea-67e4e80aede5.png)

### Please describe where this component is currently in use

The newsletter form appears on most pages on www.mozilla.org, though on that site it's a macro so shouldn't be too hard to update globally.

**Comment by craigcook** [comment]
Also we could rename "tagline" to "desc" (description) which we've used elsewhere

**Comment by stephaniehobson** [comment]
Moving away from the newsletter component.
