### ISSUE TITLE
Improving Navbar  -Adding CSS to Navbar

### ISSUE THREAD

**Issue by Aakash2408** [mozilla/protocol#582]
### Sticky Navbar Frontend 

We have a black background navbar on the left-hand side , But items on the list are left-aligned and with an underline . They look so much basic and boring.

![protocol mozilla org_](https://user-images.githubusercontent.com/47134609/81483024-c0f0b800-9258-11ea-8a67-d6351057f638.png)
 
This is how the navbar look now 

### Making changes in the navbar
I am trying to make it a bit better by  improvising CSS of links and nav items
![localhost_3000_](https://user-images.githubusercontent.com/47134609/81483048-f0072980-9258-11ea-8e5c-bc31792bec0b.png)
This is how the navbar will look after my changes on the home page. Actually, I have made changes in Locals

![Uploading localhost_3000_fundamentals_principles.html.png…]()

And on other pages, I have removed that line break white line and it looks as in the picture.

### Why these changes?

These changes make the frontend of the navbar look better than the previous part.
I have also added a hamburger icon using HTML  in place of Text "Menu".
![menuold](https://user-images.githubusercontent.com/47134609/81483908-1fb93000-925f-11ea-8296-1b82ec511190.png)
The current version of the mobile version menu

### Mobile version pictures after changing 
![mobile version](https://user-images.githubusercontent.com/47134609/81483931-4e370b00-925f-11ea-9490-26cd69d93f2f.png)
Navbar on Home page

![mobileversion2](https://user-images.githubusercontent.com/47134609/81483944-63ac3500-925f-11ea-84c2-05cad06eb2d3.png)
Navbar on other pages

### Please describe where this component is currently in use

Navbar component is already in use, I am improvising the frontend of Navbar.

### Is the development of this component a blocking dependency for other work? 

No, it is not going to affect anything on the webpage.

#583

**Comment by Aakash2408** [comment]
Can someone assign it to me?I have already made a pull request for this change.

**Comment by tikhsuP** [comment]
Thanks for your interest, @Aakash2408.

Kindly wait till a community member replies to your messages/ PRs. They will provide you help regarding this issue. You can try to reach out to them through emails. 

Thanks again :)

**Comment by craigcook** [comment]
No longer relevant since we migrated docs to Fractal. Closing. Thanks!
