### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by mheubusch** [mozilla/protocol#588]
Design tabs for progressive disclosure of content. Leverage existing precedent from SUMO if possible. 

### Please describe the use case(s) for this component

What does the component do? In what contexts is it used. Be as specific as possible.

### Please provide any designs or previous implementations of the proposed component

Add screenshots, mockups, code prototypes, etc. in this section.

## Please describe what this component does in the following conditions

* When set in front of a dark background
* When set in front of a light background
* When viewed in a mobile/responsive viewport

### Please provide examples of this type of component in use in non-Mozilla web properties

Add screenshots and links to web properties that use a similar component.
(We ask for this because we want to make sure we are following industry conventions while building components)

### Is the development of this component a blocking dependency for other work? Please explain if so

Generally speaking component definition should happen after a singleton instance has been developed,
or if the Protocol team has come to a consensus on need.

**Comment by stephaniehobson** [comment]
Not enough info to proceed.
