### ISSUE TITLE
menu-list-download.hbs demo doesn't work

### ISSUE THREAD

**Issue by Pike** [mozilla/protocol#590]
## Description

If I compare https://protocol.mozilla.org/patterns/molecules/menu-list.html# with https://www.mozilla.org/en-US/firefox/enterprise/, it seems that the demo one doesn't work?

### Expected result

The download/cta style menulist should differ from the non-modified.

### Environment

Happens on Firefox, both release and nightly

**Comment by stephaniehobson** [comment]
Tracking in #550
