### ISSUE TITLE
Typography docs are outdated and could use some improvement

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#591]
## Description

The [typography scale example](https://protocol.mozilla.org/fundamentals/typography.html#styles) in the Protocol documentation site is out of date, and does not yet reflect the new naming conventions that were added in https://github.com/mozilla/protocol/pull/555.

It would also be _really_ useful if the documentation here detailed the breakpoint sizing for each mixin. I often find myself needing to to dive into the [source code](https://github.com/mozilla/protocol/blob/master/src/assets/sass/protocol/includes/mixins/_typography.scss) to double check things.

### Steps to reproduce

Open https://protocol.mozilla.org/fundamentals/typography.html#styles

### Expected result

The example should use the new naming conventions such as `text-title-xxl`.

### Actual result

The example still references `text-display-xxl` etc:

![image](https://user-images.githubusercontent.com/400117/82201006-a02eff00-98f7-11ea-8612-e67ec2a09451.png)

### Environment

N/A

**Comment by alexgibson** [comment]
It would also be nice if the pseudo content values were a little more descriptive for what each value in the example represents: https://github.com/mozilla/protocol/blob/master/src/assets/sass/demos/type-scale.scss#L55

**Comment by nilayrajderkar** [comment]
@alexgibson should instances of the word 'Display' in the example be changed to 'Title' in the documentation? Also if this issue has not been taken up, can I try working on it?

**Comment by craigcook** [comment]
I'm updating these docs as part of [updating the type scale(s)](https://github.com/mozilla/protocol/issues/410) which is in turn part of [theming](https://github.com/mozilla/protocol/issues/447).

**Comment by Rudresh22** [comment]
Hello, can I work on this issue?
