### ISSUE TITLE
Update Button Focus State to match other focus states within protocol

### ISSUE THREAD

**Issue by dzingeek** [mozilla/protocol#594]
After updating focus states for [text links](https://github.com/mozilla/protocol/issues/589) and [inline links](https://github.com/mozilla/protocol/issues/428) to make them more accessible we realized we should do the same for the buttons.

**Comment by Rudresh22** [comment]
Hello, I want to work on this issue. Please guide me through this.

**Comment by dzingeek** [comment]
@Rudresh22 here are the new specs for the focus state for our buttons. Please let me know if you have any questions or need more guidance. 

**image showing button focus state for reference**
![image showing button focus state for reference](https://user-images.githubusercontent.com/3740746/86183874-d01d1500-bae7-11ea-8602-8b8cc4928dae.png)


**focus state specs are as followed:**

- Border-radius: **2px for sm buttons and 4px for md, lg and lx buttons sizes**
- Outer border: **#0060DF 30%, 2px**  
- Middle border: **#FFFFFF, 1px**
-  Inner boarder: **#0060DF, 2px**

**Comment by Rudresh22** [comment]
@dzingeek On it thanks.

**Comment by Rudresh22** [comment]
Hello, @dzingeek ma'am, I seem to be having a linebreak error while running 'npm start' and hence I am not able to start the development server. Can I make the changes without running the development server?

**Comment by dzingeek** [comment]
@craigcook can you help with the above?

**Comment by craigcook** [comment]
What is the error?

`npm start` will install all dependencies, then build Protocol and start the server. Alternatively you can run `npm install` just to get the dependencies, then `gulp --dev` to build and start the server. Running them separately might help you isolate an error. And once it's installed you don't need to reinstall every time you want to work on it, you can just do `gulp --dev` from then on.

**Comment by Rudresh22** [comment]
@dzingeek ma'am, I should make the changes for the given specs in the _button.scss file right? Very sorry for the inconvenience, I am a little new to OS.

**Comment by craigcook** [comment]
Yes, the file is `components/_button.scss`

**Comment by reemhamz** [comment]
Closed w/ #864
