### ISSUE TITLE
Navigation Mobile View & Close Button

### ISSUE THREAD

**Issue by AveryBuehler** [mozilla/protocol#596]
## Description

The navigation 'organism' is not working as per the [demo](https://protocol.mozilla.org/demos/navigation.html) out-of-the-box. The collapsable navigation menu remains visible on smaller screens (i.e., mobile devices), the hamburger does not appear in the top-right corner, the plus icons do not appear next to the navigation titles, and the "sticky" navigation feature does not work either. The close button also does not appear on desktop in the top-right.

### Steps to reproduce

Simply use the provided [navigation snippet](https://protocol.mozilla.org/patterns/organisms/navigation.html).

### Expected result

The navigation menu should not be visible on mobile devices, and the hamburger should appear. The plus icons should also become visible to expand each navigation title's respective content panel. The "sticky" navigation feature in the header should work as well. 

### Actual result

None of the above happened. 

#### Image of the navigation menu not collapsing and not including the plus icons on a mobile screen. 
![not_fine](https://user-images.githubusercontent.com/30603492/83598626-368a3400-a538-11ea-9c90-fad91038c782.PNG)

### Image of the navigation menu not containing the close button in the top-right on desktop.
![not_fine2](https://user-images.githubusercontent.com/30603492/83598631-38ec8e00-a538-11ea-803d-8776c8cae865.PNG)

### Environment

Microsoft Edge Version 83.0.478.37 (Official build) (64-bit) on Windows 10 v. 1903 (18362.836)

**Comment by alexgibson** [comment]
Thanks for opening this issue,

It's a bit hard to say without a test case that you can link to, but my guess is that you probably need to include Protocol's common JS bundles in your page:

- https://github.com/mozilla/protocol/blob/master/src/assets/js/protocol/protocol-base.js
- https://github.com/mozilla/protocol/blob/master/src/assets/js/protocol/protocol-utils.js
- https://github.com/mozilla/protocol/blob/master/src/assets/js/protocol/protocol-supports.js

Note that `protocol-base.js` should go in the `<head>` of your page, before your CSS.

Sorry it's not obvious, as our getting started docs are not really fleshed out yet. See https://github.com/mozilla/protocol/issues/376 for more info.

**Comment by AveryBuehler** [comment]
> Thanks for opening this issue,
> 
> It's a bit hard to say without a test case that you can link to, but my guess is that you probably need to include Protocol's common JS bundles in your page:
> 
> * https://github.com/mozilla/protocol/blob/master/src/assets/js/protocol/protocol-base.js
> * https://github.com/mozilla/protocol/blob/master/src/assets/js/protocol/protocol-utils.js
> * https://github.com/mozilla/protocol/blob/master/src/assets/js/protocol/protocol-supports.js
> 
> Note that `protocol-base.js` should go in the `<head>` of your page, before your CSS.
> 
> Sorry it's not obvious, as our getting started docs are not really fleshed out yet. See #376 for more info.

Hey Alex,

I tried what you suggested but I'm still seeing the same issues. For reference, I'm using Angular 9.1 and copied the relevant JS bundles into my `assets` folder. I've placed the three bundles mentioned above in `index.html` in the `<head>` but the issues still persist.

**Comment by alexgibson** [comment]
Can you please provide a reduced test case? It’s a little hard to debug this without being able to see some code.

**Comment by alexgibson** [comment]
Thanks for providing a test case, I’ll take a look and see what I can suggest.

**Comment by alexgibson** [comment]
When I run `npm install` on your test case it fails with the error:

```
Error: Cannot find module 'nan'
```

From there on, the install steps in the readme don't work.

So, I wasn't able to get your project running locally, but taking a look at your code, try adding a default class of[`no-js`](https://github.com/mozilla/protocol/blob/master/src/templates/blank.hbs#L2) to your base HTML file. This is needed by [`protocol-base.js`](https://github.com/mozilla/protocol/blob/master/src/assets/js/protocol/protocol-base.js#L19), and acts as a style hook for some components.

If you can fix your example project, I'd be happy to take a closer look again.

**Comment by AveryBuehler** [comment]
> When I run `npm install` on your test case it fails with the error:
> 
> ```
> Error: Cannot find module 'nan'
> ```
> 
> From there on, the install steps in the readme don't work.
> 
> So, I wasn't able to get your project running locally, but taking a look at your code, try adding a default class of[`no-js`](https://github.com/mozilla/protocol/blob/master/src/templates/blank.hbs#L2) to your base HTML file. This is needed by [`protocol-base.js`](https://github.com/mozilla/protocol/blob/master/src/assets/js/protocol/protocol-base.js#L19), and acts as a style hook for some components.
> 
> If you can fix your example project, I'd be happy to take a closer look again.

Interesting.. I was able to clone the repository and run `npm install` without any errors. Do you see anything in the error logs file? You could also try installing `nan` independently (`npm i -g nan` & `export NODE_PATH=$(npm root -g)`). 

I tried adding the default class of `no-js` to my base HTML file and it fixed *some* of the issues, but not all of them. The navigation menu is now hidden on mobile view-ports and the hamburger icon is displayed, but that's it. The hamburger icon does not work (i.e., not clickable), so the navigation menu can never be seen. The close button is also not appearing in the top-right corner in the desktop view still.

**Comment by alexgibson** [comment]
Ok, I managed to install your project by adding `nan` as a local dependency. You may want to include this locally as opposed to globally if it's a dependency.

I was able to reproduce the relative path issue, for which I filed https://github.com/mozilla/protocol/issues/597.

When running you project locally it looks like neither `protocol-navigation.js` nor `protocol-menu.js` are being included in the page. I think this is because Angular is stripping out the inline `<script>` tags when it renders the navigation. So you'll likely need to handle this in however Angular recommends. I don't think this is a bug in Protocol, more your local setup.

You'll also need to initialize the navigation in addition to the menu:

```javascript
Mzp.Navigation.init();
```

**Comment by AveryBuehler** [comment]
> Ok, I managed to install your project by adding `nan` as a local dependency. You may want to include this locally as opposed to globally if it's a dependency.
> 
> I was able to reproduce the relative path issue, for which I filed #597.
> 
> When running your project locally it looks like neither `protocol-navigation.js` nor `protocol-menu.js` are being included in the page. I think this is because Angular is stripping out the inline `<script>` tags when it renders the navigation. So you'll likely need to handle this in however Angular recommends. I don't think this is a bug in Protocol, more your local setup.
> 
> You'll also need to initialize the navigation in addition to the menu:
> 
> ```js
> Mzp.Navigation.init();
> ```

I forgot to edit my post, sorry about that. I **did** notice that the scripts weren't being included on the page, so I moved them to the `<head>` of `index.html` for testing. Even when loaded on the page, however, the aforementioned issues still persist.

**Comment by alexgibson** [comment]
You may need to initiate the components once they are loaded by Angular. If you include them in the page template and try to run separately, then they will try to initiate before the nav has been loaded in the DOM by Angular. I’m pretty certain this is an issue with your project setup, as opposed to Protocol itself. I’m sorry, but I don’t have capacity to help debug this much further, unless you can demonstrate that it’s a problem with protocol itself. A reduced test case would work here.

The relative paths in protocol-extra.scss were definitely a big, and should be fixed in the next release. Thank you for pointing it out 🙂

**Comment by AveryBuehler** [comment]
> You may need to initiate the components once they are loaded by Angular. If you include them in the page template and try to run separately, then they will try to initiate before the nav has been loaded in the DOM by Angular. I’m pretty certain this is an issue with your project setup, as opposed to Protocol itself. I’m sorry, but I don’t have capacity to help debug this much further, unless you can demonstrate that it’s a problem with protocol itself. A reduced test case would work here.
> 
> The relative paths in protocol-extra.scss were definitely a bug, and should be fixed in the next release. Thank you for pointing it out 🙂

Not a problem - I appreciate your insight! I'll continue to debug on my own and *hopefully* get everything working as intended. Thanks again.
