### ISSUE TITLE
Button click-state styling is inconsistent in Chrome

### ISSUE THREAD

**Issue by stevejalim** [mozilla/protocol#602]
## Description

Clicking a Protocol button in latest Chrome shows a blue, rounded-corner border that looks inconsistent.

### Steps to reproduce

Go to https://protocol.mozilla.org/patterns/atoms/buttons.html with Chrome (eg 83.0.4103.97 MacOS)

Click on a button.

### Expected result

Should look like this (from Firefox):

![Screenshot 2020-06-12 at 14 03 36](https://user-images.githubusercontent.com/101457/84505436-9bbaf380-acb5-11ea-94f2-dbdabea36901.png)

### Actual result

![Screenshot 2020-06-12 at 13 09 13](https://user-images.githubusercontent.com/101457/84505229-4a126900-acb5-11ea-88f2-5e7dc1da0cc1.png)

### Environment

Chrome 83.0.4103.97 MacOS Catalina 10.5.5

What browser and operating system are you using?

**Comment by stevejalim** [comment]
Further, just noticed this in Edge Beta on MacOS:

![Screenshot 2020-06-12 at 14 06 13](https://user-images.githubusercontent.com/101457/84505606-ee94ab00-acb5-11ea-9551-7e7c885bbcb0.png)

(I haven't checked Safari yet because it's glitching on my machine, but am sure someone will when tackling this bug)

**Comment by craigcook** [comment]
I get a white focus ring in my Chrome, not blue, but that might be attributable to some local preference setting either in Chrome or macOS. I'm not sure if something changed recently in Blink/Chromium or if our buttons have always had this issue...

But in any case, these buttons are changing in the next Protocol release (see https://github.com/mozilla/protocol/issues/429) so this issue should soon become moot. I'll leave it open for the moment until we finally publish 12.0.

**Comment by stevejalim** [comment]
Thanks @craigcook - it's definitely a new thing/moved goalposts, rather than a long-standing bug, else am pretty sure I would have seen it before, given how often am clicking on them during development.

Does #429 fully replace the current button style? (Am fine with that, just wondering how big a change to expect/to have to QA on my stuff 😄 )

**Comment by stephaniehobson** [comment]
Chrome[ just changed all their form element default styles](https://css-tricks.com/chrome-83-form-element-styles/)  🤦‍♀️ We should double check before we publish 12.

**Comment by craigcook** [comment]
There's also this recent issue to update focus styles on buttons, so this change in Chrome is another thing to factor in https://github.com/mozilla/protocol/issues/594

**Comment by stephaniehobson** [comment]
Tracking in #594
