### ISSUE TITLE
Sticky Promo Card

### ISSUE THREAD

**Issue by justinkropp** [mozilla/protocol#603]
### Please describe the use case(s) for this component
The Sticky Promo Card is a fixed floating content block used to:
- promote a product, service, or series of products
- provide a download CTA

What does the component do? In what contexts is it used. Be as specific as possible.

The Promo Card slides in as the user reaches a certain position on the page. As the user scrolls back up the sticky promo slides back on the canvas.

### Please provide any designs or previous implementations of the proposed component

The attached design is a work in progress and refined design and ux documentation is needed

![fx-1312 sticky download iterations](https://user-images.githubusercontent.com/1461798/85326481-5c518b80-b49b-11ea-9efb-04a48ee5ab9b.png)

## Please describe what this component does in the following conditions

TBD

* When set in front of a dark background
* When set in front of a light background
* When viewed in a mobile/responsive viewport

### Please provide examples of this type of component in use in non-Mozilla web properties

TBD

### Is the development of this component a blocking dependency for other work? Please explain if so

TBD

**Comment by amychurchwell** [comment]
Hi @justinkropp! Started working on a rough draft PR for this. Is the documentation finalized? or still being refined?

**Comment by justinkropp** [comment]
Hey @amychurchwell. I've attached the visual specs for the promo card, which you should consider a work in progress. That being said, it should provide enough to compare the prototype to. I don't foresee any big changes to these specs.


![Sticky Promo](https://user-images.githubusercontent.com/1461798/87551921-037ea880-c67f-11ea-9813-d72005a5df40.png)
