### ISSUE TITLE
Standardize data attributes in protocol for GTM

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/protocol#613]
## Description

I would like the explore the possibility of using protocol as a lever to standardize attribution on Mozilla websites. If our goal is to one day have websites across Mozilla consuming the protocol, I wonder if we could also ship tests for [data attributes & expected values](https://bedrock.readthedocs.io/en/latest/analytics.html#gtm-listeners-data-attributes) for elements within the library. (Currently, this is something the web developer just needs to know to do and in what way data science expects.)

Perhaps this could be a supplementary library like how we have for [logos and assets](https://github.com/mozilla/protocol-assets/), so users could opt-in? Open to discuss.

**Comment by amychurchwell** [comment]
@craigcook @stephaniehobson would love to know your initial reactions as you are the closest devs to protocol at the moment.

**Comment by amychurchwell** [comment]
We are potentially moving away from GA/GTM. Depends on: https://github.com/mozilla/bedrock/issues/7083

**Comment by stephaniehobson** [comment]
Still a good idea but analytics are in too much of a flux to finalize anything. Will re-open if it comes up again.
