### ISSUE TITLE
'lintCSS' errored after 4.48 s

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#616]
I'm getting an error when I try to run `npm start`. I think it may be related to #608.

```
[23:12:33] 'lintCSS' errored after 4.48 s
[23:12:33] TypeError in plugin "gulp-stylelint"
Message:
    args.trimStart is not a function
Details:
    postcssNode: background-image: url('#{$image-path}/icons/video-card.svg')
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

**Comment by alexgibson** [comment]
@stephaniehobson things seem ok on the master branch and in CI. Might you be running an outdated version of Node perhaps? What does `node -v` say?

**Comment by alexgibson** [comment]
I can't reproduce this on Node v12, and we're running v10 in CI which also seems ok.

**Comment by stephaniehobson** [comment]
That fixed it 👍
