### ISSUE TITLE
Small typo on forms page.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/protocol#624]
## Description

Small typo on [molecules/forms](https://protocol.mozilla.org/patterns/molecules/forms.html)
https://github.com/mozilla/protocol/blob/29da067fae5474cf7aeb84bc0fe58fd93bc29e3b/src/patterns/molecules/forms/custom-checks.hbs#L3

Update `precicely` to `precisely`

**Comment by amychurchwell** [comment]
This is a great beginner bug for anyone out there who would like to contribute a PR.

**Comment by rochisha0** [comment]
Hey! I'll like to contribute.

**Comment by rochisha0** [comment]
I think this has been already fixed. This issue can be closed. :)
