### ISSUE TITLE
Add mzp-t-dark to fundamentals/themes

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/protocol#628]
## Description

Add an example of using `mzp-t-dark` to fundamentals/themes

**Comment by craigcook** [comment]
That page is changing a lot in https://github.com/mozilla/protocol/pull/609. 

We don't have a really fleshed out dark theme and I want to work on that soon. In the interim I can try to add some documentation of the rudimentary dark theme we do have.

**Comment by amychurchwell** [comment]
@craigcook We have it on a per-component basis, which I think is worth calling out even if it's not a body tag theme yet.

**Comment by rochisha0** [comment]
Can I work on this @amychurchwell ?

**Comment by craigcook** [comment]
> Can I work on this @amychurchwell ?

Sorry, this is already being addressed in https://github.com/mozilla/protocol/pull/609, I should have assigned myself.

**Comment by stephaniehobson** [comment]
Dark themes are documented on a per-component basis (we don't have dark brand themes... yet).
