### ISSUE TITLE
Link preview article cards

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#64]
It would be great if we could take the cards we created for the homepage and re-purpose them as link previews. Here's a poorly written [codepen](https://codepen.io/michaelmccombie/full/qYZyyp/) with an example of this feature.

![article-card-preview](https://user-images.githubusercontent.com/5924575/39158083-ee7abd9a-4712-11e8-8aef-afa27d7aada8.png)

**Comment by michaelmccombie** [comment]
tim lillis brought up a good point during our design review. We should look in to using open-graph data to pull this off. http://ogp.me/

**Comment by stephaniehobson** [comment]
I'm going to close this issue until we have a page that demonstrates a need for a component like this.
