### ISSUE TITLE
Backport Section Heading from bedrock

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#664]
Several pages in bedrock have custom "section title"s. We should backport and standardize.

I'm particularly fond of https://github.com/mozilla/bedrock/blob/53741200257a192422e1a11ec4defdf1a50c84c4/media/css/firefox/new/desktop/download.scss#L281-L291 but, you know, I wrote it.

**Comment by craigcook** [comment]
See also https://github.com/mozilla/protocol/issues/235
