### ISSUE TITLE
Add brand themes for Mozilla VPN and Pocket

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#729]
Mozilla VPN and Pocket have distinct brand elements (fonts, colors, common motifs) that don't currently reside in Protocol. We should add them.

Mozilla VPN is mostly the same as the Mozilla brand, with a black and white dominant palette and Zilla Slab for headings, but it uses purple as an accent color and is mostly distinguished by the "offset shadow" box style.

![image](https://user-images.githubusercontent.com/205591/134549868-f38ed908-ebb0-4519-8c92-5ce8f7947094.png)

Pocket has a whole color palette that we'll need to add as new tokens, and its own set of fonts that we'll need to add as well. They use Doyle for headlines and Graphik Web for body copy (I also see Blanco OSF in their CSS but I'm not sure where that gets used in practice, so maybe it could be eliminated).

![image](https://user-images.githubusercontent.com/205591/134551810-9e21626a-dfd4-43ff-9dd5-8f159a51bcf2.png)

**Comment by craigcook** [comment]
Also filed https://github.com/mozilla/protocol-tokens/issues/97 for Pocket tokens

**Comment by reemhamz** [comment]
I'll be reaching out to the Pocket design team to work together and get what we need to add their product branding into Protocol. I assume we should also be doing the same for the VPN team. Has there been any movement on reaching out to the VPN team yet? @craigcook
