### ISSUE TITLE
Migrate Protocol documentation to Fractal

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#759]
The Protocol doc site (https://protocol.mozilla.org) was initially built with Drizzle, a platform that has since been officially deprecated and will no longer be updated. We've opted to migrate to Fractal (https://fractal.build) for our documentation but that migration will entail a number of steps.

This issue can serve as an epic tracking the full migration and we'll break it down into individual tasks under this umbrella.

Project board: https://github.com/mozilla/protocol/projects/10

**Comment by craigcook** [comment]
We have a branch for all the Fractal migration work: https://github.com/mozilla/protocol/tree/fractal.

Though it started as a branch from `main`, the first thing I did was delete almost everything except the core assets and then started adding new things from scratch. So the new branch is such a radical diversion that it hardly seems worth trying to merge it to main. Instead, my idea is to eventually archive the `main` branch and rename the `fractal` branch to `main`. 

So meanwhile we still have a canonical `main` branch that reflects the current state of Protocol and we can do all our migration work in the `fractal` branch. We should avoid doing much real work in `main` but could still add any important fixes there that need to be published before Fractal is ready (and we may need to migrate those fixes to the `fractal` branch by hand).

I've been making direct commits to `fractal` so far but now that a sort of baseline has been established I intend to start making pull requests to that branch for review.

**Comment by reemhamz** [comment]
Hey developers, here's how we run this branch:
First, make sure you run `npm install`. You're going to need 2 terminal windows running.
- In one, type `npm run webpack-docs`
- In the other, type `npm start` and follow the localhost URL.

**Comment by craigcook** [comment]
Let's edit the checklist comment above to put our names next to any components we're claiming, to avoid more than one person working on the same thing.

We could also create an issue for each one but that feels like a lot.

**Comment by reemhamz** [comment]
Very odd, I didn't get that either.

**Comment by nathan-barrett** [comment]
I actually got this, but it happened when I ran `npm build` on the `main` branch

**Comment by reemhamz** [comment]
Are we supposed to run `npm build`?

**Comment by craigcook** [comment]
> Are we supposed to run `npm build`?

No, just `npm start`. The fractal branch doesn't have a `src` folder at all, so if anything that's a leftover from switching branches. We could add it to gitignore if this keeps happening.

**Comment by nathan-barrett** [comment]
Sorry, no - I was just seeing how the webpack build worked in protocol to help when I was working on trafficcop

**Comment by maureenlholland** [comment]
Ah, thanks @nathan-barrett that explains it. Yes, I probably had this folder hanging out in my workspace for a while but the current `main` branch excludes them so I never noticed. Mystery solved! +1 on not including in the fractal .gitignore

**Comment by craigcook** [comment]
Migration complete! The old [Drizzle-based main branch has been archived](https://github.com/mozilla/protocol/tree/main-archive-20220629) and the Fractal-based working branch has become the new main branch. 

That required force-pushing to `main` so you may get some funkiness locally when you rebase but hopefully relatively painless (and you'll need to force-push `main` on your remote forks).

Thanks everybody!
