### ISSUE TITLE
Component Change 

### ISSUE THREAD

**Issue by artra5253** [mozilla/protocol#762]
Please use this template to request changes to an existing component.

If you're not sure whether a component already exists,
probably better to just file a new component request and let the Protocol Team triage.

Fill in as many sections as possible below.

### Please describe the use case(s) for this component

What does the component do? In what contexts is it used. Be as specific as possible.

### Please describe the change you wish to see

What's changing?

### Please describe why these changes need to be made

And why

### Please provide any designs or prototypes of the proposed changes

Add screenshots, mockups, code prototypes, etc. in this section.

### Please describe where this component is currently in use

In order to assess the risk of changes, we need to know where components exist in the wild.

### Please describe what this component should do in the following conditions

* When set in front of a dark background
* When set in front of a light background
* When viewed in a mobile/responsive viewport

### Is the development of this component a blocking dependency for other work? Please explain if so

Generally speaking, component definition should happen after a singleton instance has been developed,
or if the Protocol team has come to a consensus on need. If this is a rush job/or blocking dependency
- [ ] please describe why this is needed.

**Comment by craigcook** [comment]
There was no information provided so I'm assuming this was a mistake. If you have a request feel free to reopen with more info.
