### ISSUE TITLE
Component Request: Dropdown Button for Input

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/protocol#765]
Please use this template to request changes to an existing component.

If you're not sure whether a component already exists,
probably better to just file a new component request and let the Protocol Team triage.

Fill in as many sections as possible below.

### Please describe the use case(s) for this component

Add a dropdown button for input field, like [button dropdown in Bootstrap](https://getbootstrap.com/docs/5.1/forms/input-group/#buttons-with-dropdowns)

My particular use case in a search field for comparing the performance results of different revisions. The dropdown would be to select the repo to search (try, autoland, mozilla-central)

### Please describe the change you wish to see
Implement a bootstrap-like feature with the protocol design

### Please provide any designs or prototypes of the proposed changes

![image](https://user-images.githubusercontent.com/18633586/152665349-e3df31bd-4f98-4541-b7b6-b78e94aad403.png)

![image](https://user-images.githubusercontent.com/18633586/152665400-d271c8ed-af30-4948-bdb1-dac6d291723d.png)

### Please describe where this component is currently in use

Should not affect existing input fields, would be an optional addition

### Is the development of this component a blocking dependency for other work? Please explain if so

This is to be used in a project for the Performance Test team scheduled to take several months, with a demo planned for the All Hands in September

**Comment by craigcook** [comment]
Sorry it took so long to follow up here. This is a pretty specialized widget that I'm not sure has a common enough use case for Protocol at this time. If you have a specific need for it on your project I think you'll be better off implementing your own version.

If you did want to get an equivalent capability with existing form elements it could easily be a separate select combined with a search input.
