### ISSUE TITLE
Remove default mobile padding on nospace split component

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/protocol#779]
Related to a bedrock issue & PR:
https://github.com/mozilla/bedrock/issues/11457
https://github.com/mozilla/bedrock/pull/11512#issuecomment-1104545527

We currently include top and bottom padding on nospace split components up until the medium media query, where the spacing is removed.

This causes a noticeable gap on mobile when sibling elements have different background colors.

Should we leave as-is and consider this an edge case users can manually override? (If so, worth adding a note in the docs to watch out for this potential issue)
Should we make no space on mobile the default?
Should we provide a utility mobile class to remove space as needed?

In bedrock, we have 34 uses of `mzp-t-split-nospace`
https://github.com/mozilla/bedrock/search?l=HTML&q=mzp-t-split-nospace
about 10 need the mobile padding removed because the gap is visible

**Comment by craigcook** [comment]
I wonder if we could combine it with the `mzp-c-split-bg` class to zero the padding only when there's a background color... though the bg class appears on an element _inside_ the one with the nospace class so I'm not sure how to select for that.

**Comment by maureenlholland** [comment]
Yeah, would be a good use for `.mzp-t-split-nospace:has(.mzp-c-split-bg)` selector but there's [not enough support ](https://caniuse.com/?search=%3Ahas())

To avoid complicating things, I'd go for a small note on the split nospace component docs that this is a potential issue to keep in mind.

**Comment by stephaniehobson** [comment]
We should backport what was already done in bedrock. No space should be no space on mobile too.
