### ISSUE TITLE
Add a style rule for the `hidden` attribute.

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol#783]
## Description

The global `hidden` attribute indicates that an element is not relevant and shouldn't be rendered ([see MDN](https://developer.mozilla.org/docs/Web/HTML/Global_attributes/hidden)). Modern browsers treat it as equivalent to CSS `display: none` but old browsers don't recognize the attribute and will still render the element.

We should add a style rule to our global reset:

`[hidden] { display: none; }`

Especially old browsers that don't support attribute selectors will ignore this as well and still render the element. But most notably IE9 and 10 **DO** support attribute selectors but **DO NOT** support the `hidden` attribute, so adding this rule to our baseline styles will cover those cases.

**Comment by architsinghal-mriirs** [comment]
Hi. @craigcook  Please assign this issue to me.
