### ISSUE TITLE
Consider using variable font for Inter

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#805]
### Please describe the use case(s) for this component

Inter is now available in variable font format, as well as a standard web font: https://rsms.me/inter/

### Please describe the change you wish to see

For browsers that support variable fonts, it would be nice if they used the new format, whilst older browsers continue to use the standard fonts.

### Please describe why these changes need to be made

Variable fonts support multiple weights in a single file, so it might be a nice performance win for newer browsers.

### Please provide any designs or prototypes of the proposed changes

There's an article here that details how to implement variable fonts whilst still supporting older browsers: https://pimpmytype.com/variable-font-fallback/

### Is the development of this component a blocking dependency for other work? Please explain if so

No

**Comment by Draxgee** [comment]
Nice to try

**Comment by alexgibson** [comment]
I'm going to close this as wontfix.

The Inter variable font works well, but the performance trade off only seems worth it on pages where we load regular, bold and italic font styles. On mozorg at least, we typically only load 2 weights, not 3.
