### ISSUE TITLE
Previous URLs are broken with new docs

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/protocol#812]
## Description

I have a few specific pages bookmarked from the Protocol docs site. (https://protocol.mozilla.org/fundamentals/tokens.html) 

### Steps to reproduce

- Go to https://protocol.mozilla.org/fundamentals/tokens.html
- Expected: Page loads correct "tokens" page
- Actual: 404 Error. 

### Expected result

- The old URLs redirect to the new pages. (https://protocol.mozilla.org/docs/fundamentals/design-tokens.html) 

### Actual result

404 Page Not Found

### Environment

N/A

**Comment by craigcook** [comment]
Fixed with https://github.com/mozilla/protocol/pull/846
