### ISSUE TITLE
Update .stylelintrc to match config from 'mozilla/bedrock'

### ISSUE THREAD

**Issue by nathan-barrett** [mozilla/protocol#814]
## Description

Update the existing `.stylelintrc` file to extend the `stylelint-config-standard-scss` rules and match the config file in `mozilla/bedrock` [here](https://github.com/mozilla/bedrock/blob/main/.stylelintrc)

### Success Criteria

- [ ] `.stylelintrc` has been updated 
- [ ]  affected files have been reformatted

**Comment by nathan-barrett** [comment]
@katiechurchwell assigned! A couple notes I forgot to mention:
- [ ] the library `stylelint-config-standard-scss` will need to be added via npm
- [ ] run `npm run lint-css` to lint all `.scss` files before your PR so that the files have been reformatted correctly

**Comment by katiechurchwell** [comment]
@nathan-barrett Ok, I have a quick update and a question for you!

 - :heavy_check_mark: Extended and added the dependency for `stylelint-config-standard-scss`
- Partially reformatted when running `npx stylelint "**/*.scss" --fix`
  - `npm run lint-css` doesn't work for me which makes me feel like the script should be updated?
  - getting a lot of `no-descending-specificity` messages so figuring out what that means. I think it has to do with how the custom rules are written?
- When you say "match the config file in `mozilla/bedrock`", do you want the file to look exactly like that or just the rules?

Thanks! :cowboy_hat_face:

**Comment by nathan-barrett** [comment]
Cool! Nice work @katiechurchwell - I think I miscommunicated what the best way to do this - I think that the `.stylelintrc` file in protocol should contain the same rules that are found inside the bedrock repo - but also keep the existing rules that are in place in protocol.  If there are two matching and/or conflicting rules - we should use the preference set in bedrock.  

Let me know if any of that doesn't make sense.

As for the `no-descending-specificity` messages - its coming from this rule [here](https://stylelint.io/user-guide/rules/list/no-descending-specificity/).

**Comment by katiechurchwell** [comment]
@nathan-barrett Hi Nathan, I wanted to provide an update on this issue. It's coming along but I'm concerned about some of the linting rules causing some breaking changes; kebab case and no global function names in particular. I could go ahead and format everything and submit a PR to have you check it out but I wanted to doublecheck these are the intended changes.

**Comment by nathan-barrett** [comment]
@katiechurchwell good call out! Lets keep the duplicated variable names. 

As for the rest, lets create a PR and I can take a look to see how much it changes and we can see what the best path forward is! Thanks @katiechurchwell

**Comment by katiechurchwell** [comment]
@nathan-barrett Great! Noobie problem but I'm looking into how to create a PR as I don't have permission to create a new branch... would I use moz-phab for that...? Sorry!  :sweat_smile:

**Comment by nathan-barrett** [comment]
No problem! Best way to do this would be to create your own fork of protocol on github - and then add that fork to your list of remotes on your local repo:
```
git remote add origin ${yourforksname}
git push origin ${branchname}
```
(you don't have to use origin for your own fork, but I find it easiest)

Once you push your commits up to your fork you should have the option to open a pull request. Happy to help if you have anymore questions
