### ISSUE TITLE
Make `<code>` elements easier to distinguish

### ISSUE THREAD

**Issue by Rexogamer** [mozilla/protocol#822]
Originally mentioned in mozilla/kitsune#5037, `<code>` elements are currently rather hard to distinguish (image from the issue's creator):

![image](https://user-images.githubusercontent.com/42586271/188516402-ab1f574b-4231-40d1-8c41-84f8562590e7.png)

They would be more discernable with some sort of background/border - here's a mockup I made:

![image](https://user-images.githubusercontent.com/42586271/188516597-c5e95963-0ded-4b10-8ac7-f3cf0a4759ba.png)

For reference, here's the CSS I used for the mockup:

```
code {
  font-size: .875em;
  background: var(--color-light-gray-03);
  border: 2px solid var(--color-light-gray-05);
  border-radius: 3px;
  padding: 1px;
}
```

I wanted to file an issue/check with others before making a PR as I have two main questions:
- Would this change be controversial/would it cause issues for other Mozilla sites?
- Do the colours above have any kind of significant meaning or are they fine to use?

**Comment by reemhamz** [comment]
Hey @Rexogamer! Thanks for writing up this issue. 
Protocol doesn't provide styles for `<code>` tags necessarily. What you see on our site's sidebar (https://protocol.mozilla.org/) is what we essentially have designs for. Our typography section also doesn't cover the `<code>` tag. 

Digging into Kitsune's codebase, I think the underlying code that should be updated here lives in this file: https://github.com/mozilla/kitsune/blob/main/styleguide/kss-template/kss-assets/scss/base/_kss-style.scss.

There are probably other styles for this within the Kitsune codebase you can dig into, but this was just after a quick look-up. 

I'm going to close this issue as this isn't particularly a use case for Protocol to patch up. Thanks again :)

**Comment by Rexogamer** [comment]
I was looking everywhere for the relevant CSS and it was there - thanks for
the heads up ^^
