### ISSUE TITLE
Input not needing aria-disabled?

### ISSUE THREAD

**Issue by thomassth** [mozilla/protocol#823]
From multiple sources I read, `input disabled` seems to already covered the function of `aria-disabled`. But the current doc suggests to add both:

https://protocol.mozilla.org/components/detail/input--disabled.html

Is there a reason behind it? Or can we remove that

**Comment by maureenlholland** [comment]
Sounds reasonable to remove, or clarify the separate use case for `aria-disabled`. [MDN docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled):

> Unlike HTML's [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#attr-disabled) Boolean attribute which will communicate a form control as semantically being disabled, change its styling to reflect its state, and suppress all functionality along with disallowing the element's value from participating in form submission, the aria-disabled="true" only semantically exposes these elements as being disabled.

> However, there can be instances where elements need to be exposed as disabled, but are still available for users to find when navigating via the Tab key. 

@craigcook what do you think?

**Comment by craigcook** [comment]
Agreed, we should update the docs.
