### ISSUE TITLE
Design Tokens approach

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol#83]
Let's have a discussion and put together a branch that would explore creating our design tokens deliverable files using Salesforce's Theo https://github.com/salesforce-ux/theo

**Comment by alexgibson** [comment]
Some initial thoughts:

- The current build scripts are long and could do with refactoring / simplifying.
- A third party solution such as Theo provides a nice API, which would make things much easier to read.
- Before reaching for a third party however, we should probably take stock on how complicated we can expect our tokens to get. Would switching be worth adding another dependency? How much effort would simplifying the current build scripts be without switching to something else?

**Comment by michaelmccombie** [comment]
Some thoughts on Alex's thoughts

- Definitely agree at the very least we will need to rewrite the build file(s) at some point. The way the color file was originally written didn't match up with our exacts needs so we started making adjustments on the fly (adding aliases, adding gradients, etc) while trying to squash possible bugs which is how things became a little unwieldy.
- It would also save us a bunch of time
- It is a dependency that is crucial to Salesforce's infrastructure so thankfully we won't have to worry too much about support being abandoned or critical bugs. But I agree nested dependencies aren't ideal. 

As far as what should be a token vs what should be specific to the CSS framework. I've tried to think of it in the terms below. Which is how we ended up with Colors, Assets, Type, & Layout as our four basic packages (Type still hasn't been written).
1) Do other companies consider this variable to be token worthy? 
2) Is this variable device agnostic enough to be useful elsewhere?
3) Can this be consumed by both the framework and Sketch?

**Comment by michaelmccombie** [comment]
For comparison sake this is a rough breakdown of what we use tokens (currently) compared to how Salesforce uses tokens.

| Property | Mozilla Protocol | Salesforce Theo |
| - | - | - |
| Background Color | x | x |
| Text Color              | x | x |
| Border Color          | x | x |
| Font                       |  Soon |  x |
| Font Size               |  Soon | x  |
| Gradients              | x |  |
| Opacity                  |    |  x |
| Line Height            |  Soon |  x |
| Spacing                 | x  |  x |
| Radius                   |    |  x |
| Sizing                    | x  |  x |
| Shadow                 |    |  x |
| Time                      |    |   x|
| Media Query          |  x  |  x |
| Z-index                  |    |  x |

**Comment by michaelmccombie** [comment]
For what its worth, I still haven't the time.actually thoroughly research/ play around with Theo so it could work differently than how I'm imagining it works.

**Comment by alexgibson** [comment]
Fixed in shiny new repo https://github.com/mozilla/protocol-tokens/
