### ISSUE TITLE
Performance budget calculator

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#84]
This is a long-term feature / wish - but I would *love* to build a [performance budget](https://timkadlec.com/2013/01/setting-a-performance-budget/) estimator into Protocol. Establishing a way to give performance budget estimations & guidelines in our documentation would help us to reason about how much a given web page might weigh, before we've even started building it.

I haven't thought through how it would all work, but a basic MVP could work as follows:

- After CSS/JS is compiled in the build process, run a new task that grabs the size for each processed file.
- Spit out the data into `src/data/file-sizes{.json|.yaml}` or similar.
- This data could then be used via handlebars templates, so components could display their file size inline in our documentation.
- We could also build a "budget calculator" page of sorts, where you can select different components (i.e. core, modal, card etc) and it can give you an estimated file size to weigh against a predefined budget.

**Comment by craigcook** [comment]
There's been no movement on this for a while, closing as irrelevant for now. If we want to revisit the idea at a later time we can reopen or start fresh.
