### ISSUE TITLE
Rethink JS concatenation

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#89]
Currently our build process looks in `${src}/js/protocol/*.js` and bundles everything into `${dest}/protocol/protocol/js/protocol.js`. This has the following issues:

- Some of the files in `/js/protocol/` are intended to go in the `<head>` of the page, such as `protocol-base.js`, whereas the rest are not.
- There's no easy control on the order of concatenation. It all happens alphabetically and relies solely on how files are named.
- We're writing individual JS files assuming the corresponding HTML is in the page where the JS is loaded. If we're bundling JS into one big glob and we're not careful, we're gonna run into JS errors.
- Sites will likely not want to include the JS for every component on every page. It hurts page load times and wastes people's bandwidth.

Unless anyone has objections or has reasons I've not thought about to keep the `concatJS` task, I'd like to propose we drop it, and allow sites to bundle JS as they see fit.

**Comment by craigcook** [comment]
It makes sense to keep the JS for each component separate if we intend to also keep the CSS for each component separate. I'm probably biased by how we already work in bedrock with per-page bundles where we can indicate which pieces we actually need for a given page. I want to keep working that way, and bedrock is still the first priority target for Protocol so keeping components separate is good for us.

I can imagine other sites in the future might prefer a monolith (one style sheet for the whole site, not per page) but even then they should be able to select which bits go into a custom monolith. If you don't have a sidebar menu anywhere on your site then you don't need to download those 100 extra lines of CSS. We could eventually do a Foundation-style "pick your build" thing but short term I think it would be up to any consuming site to do their own compilation/concatenation. 

We're modular like furniture. We provide the parts, you do the assembly.

**Comment by alexgibson** [comment]
> I can imagine other sites in the future might prefer a monolith (one style sheet for the whole site, not per page) but even then they should be able to select which bits go into a custom monolith. If you don't have a sidebar menu anywhere on your site then you don't need to download those 100 extra lines of CSS. We could eventually do a Foundation-style "pick your build" thing but short term I think it would be up to any consuming site to do their own compilation/concatenation.

I think in the future we'll see sites move away from monolith files. With all modern browsers supporting http2 now, it's actually more performant to include separate files in each page as opposed to bundle everything. We could build a Foundation  style "pick your build" thing, but soon it may be outdated tbh.

**Comment by craigcook** [comment]
I suppose I should study up on http2. I didn't think it was a practical choice for production yet, but maybe it is or soon will be. 

I also didn't mean we should start working on a pick-your-build tool right now, just trying to think ahead if Protocol is some day used by lots of different projects. We wouldn't build it until it was needed, and maybe if http2 is the norm that time will never come.

**Comment by alexgibson** [comment]
Fwiw, we’re discussing possibly switching to unbundled assets on bedrock soon (pending a A/B test)

**Comment by alexgibson** [comment]
> We're writing individual JS files assuming the corresponding HTML is in the page where the JS is loaded. If we're bundling JS into one big glob and we're not careful, we're gonna run into JS errors.

As an example of this, if you currently inspect the [protocol site home page](https://mozilla-protocol.netlify.com/) there's an error: `TypeError: menuToggle is null`, because the toggle menu doesn't exist on most pages.
