### ISSUE TITLE
Migrate JS tests to jasmine-browser-runner

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#899]
See https://github.com/mozilla/bedrock/issues/13423 for details.

TL:DR is karma is no longer maintained. We should migrate the Protocol tests to jasmine-browser-runner like we are doing for bedrock.

**Comment by alexgibson** [comment]
It would also be nice to add Chrome to the browsers that run Protocol's tests in CI

**Comment by alexgibson** [comment]
@reemhamz are you still working on this one? If not, I can probably find time to get this one knocked out soon

**Comment by reemhamz** [comment]
Ah yup I definitely haven't started this yet and have other things I need to work on for Protocol that are higher on my list, so feel free to go ahead with this one 👍🏼
