### ISSUE TITLE
Favicon MIME mismatch

### ISSUE THREAD

**Issue by janbrasna** [mozilla/protocol#911]
Fractal only allows .ico as favicons as the MIME type is hardcoded in mandelbrot nunjucks: [@fractal/mandelbrot:views/partials/head.nunj](https://github.com/frctl/fractal/blob/dd6cd938653b24cd23456d10b9c28d3bc436c4c3/packages/mandelbrot/views/partials/head.nunj#L1)

Passing a .png asset renders the meta as:
```html
<link rel="shortcut icon" href="./theme/favicon.png" type="image/ico">
```
(a PNG file with an image/ico MIME type)

Probably not worth addressing as reasonable clients won't trip over this — just a heads up…

**Comment by Ayushsunny** [comment]
Hey @janbrasna ,  Should i fix this?

**Comment by janbrasna** [comment]
Yo @Ayushsunny that needs to be fixed upstream in [@fractal/mandelbrot](https://github.com/frctl/fractal/blob/dd6cd938653b24cd23456d10b9c28d3bc436c4c3/packages/mandelbrot/views/partials/head.nunj#L1) — ideally by removing the type attribute completely as is the [recommendation in 2024](https://dev.to/multiwebinc/comment/1oedd) anyways… — but that project has been unmaintained for some time now:/

Fixing it locally by replacing the png with decades old lowres ico is probably not the way to resolve this;)
